### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#100]
What about new name?

Variants:
1. `Storio` — `Storage IO` `com.pushtorefresh.storio`

CC @nikitin-da

**Comment by nikitin-da** [comment]
Storio +
2. Rx Storage 
3. Rx DAO
3. Deposit =)   &#822;h&#822;t&#822;t&#822;p&#822;:&#822;/&#822;/&#822;d&#822;f&#822;i&#822;l&#822;e&#822;s&#822;.&#822;r&#822;u&#822;/&#822;r&#822;u&#822;/&#822; com.pushtorefresh.deposit

**Comment by artem-zinnatullin** [comment]
2. `Rx Storage` — too much Rx 
3. `Rx DAO` -> NO DAO, NO ORM, NO ACTIVERECORD!!11 :smile: 
4. `Deposit`? May be `DataBank`? :)

**Comment by nikitin-da** [comment]
4. DataBank - nice

**Comment by artem-zinnatullin** [comment]
`Storio` seems to be more hipster name in 2015 than `DataBank`, such as `Node.js`, `IO.js`

**Comment by nikitin-da** [comment]
On, let it be. xD

**Comment by artem-zinnatullin** [comment]
Cool, I'll rename the repo

**Comment by artem-zinnatullin** [comment]
Rename done, now rename package
