### ISSUE TITLE
Licence in all source files

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#105]
Licence text should be in header of every source file

**Comment by tsuharesu** [comment]
I am up to do this (in IntelliJ is not that hard) but... do you mind commiting the .idea folder? The copyright is stored there so it is easier (and automatic) to apply with IntelliJ/Android Studio.

I use the model in gitignore.io to check the folder so it just shares the project settings and not all the files, paths and etc (https://www.gitignore.io/api/intellij).

**Comment by artem-zinnatullin** [comment]
Yep, I know about IntelliJ setting for copyright.

I think we will create separate repository with IntelliJ settings for all Open Source projects of Pushtorefresh.

Don't worry, about Licence, it's Apache Licence v2.0, I am not sure that it'll be placed in each header in 1.0.0, but later it'll be there :)

**Comment by tsuharesu** [comment]
Hmm, how this should work? Having the settings on a difference place?

Ok, I just was looking on the issues and seeing where can I help hehe :)

**Comment by artem-zinnatullin** [comment]
Every developer would be able to close repository with IntelliJ settings and apply them to IDE and then participate in all Pushtorefresh OSS projects.

At the moment we use standard IntelliJ Java code style, so it's not a problem :)

**Comment by artem-zinnatullin** [comment]
Licence is in the repository.
