### ISSUE TITLE
Exceptions for operations

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#110]
`PutException`, `GetException`, `DeleteException`

**Comment by nikitin-da** [comment]
What do you mean? Particular class for every operation?

**Comment by artem-zinnatullin** [comment]
We have these classes, but don't use them, StorIO.Internal should throw them

сб, 14 марта 2015, 12:38, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
I thought about exceptions for couple of days and I don't see any prons of using custom `RuntimeExceptions`, nobody will catch them so, it does not matter what exception will be thrown.

I am going to delete them, @nikitin-da your opinion?

**Comment by nikitin-da** [comment]
Yes, if there are no way to use `checked`, so I also don't see profit from custom exceptions.

**Comment by artem-zinnatullin** [comment]
Okay, I'll prepare PR where I'll remove them
