### ISSUE TITLE
Rename Query.where

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#118]
`Query.where -> Query.selection`
`Query.whereArgs -> Query.selectionArgs`

For better consistency with `SQLiteDatabase#query()` and `ContentProvider#query()`.

But, actually `where` looks much more understandable than `selection`, especially for `ContentProvider`

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
I prefer `where`. Does only `dbHelper` and `contentProvider` use `selection` name? At low level `dbHelper` also translate it to `where`. %)

**Comment by artem-zinnatullin** [comment]
Hehe :) Okay, where

вт, 17 марта 2015, 0:43, Dmitrii Nikitin <notifications@github.com>:
