### ISSUE TITLE
Add more transaction methods to StorIODb

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#124]
* `inTransaction()`
* `yieldIfContendedSafely(long sleepAfterYieldDelay)`
* `yieldIfContendedSafely()`

**Comment by artem-zinnatullin** [comment]
Hm, for v1.0.0 I think it will be enough to have `inTransaction`. Actually, `yieldIfContentedSafely()` seems like a really bad method for database

**Comment by nikitin-da** [comment]
Yep. As for me `inTransaction` is also quite specific.

**Comment by artem-zinnatullin** [comment]
From `SQLiteDatabase` documentation `Returns true if the current thread has a transaction pending.`

Do you see any usages for `inTransaction()`?

**Comment by nikitin-da** [comment]
On my opinion it's a little fine tune for mobile devices.

**Comment by artem-zinnatullin** [comment]
So, let's close this for now, may be it will be added in future
