### ISSUE TITLE
Unify naming of default StorIO implementations

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#138]
Currently we have `StorIODb` + `StorIOSQLiteDb` and `StorIOContentProvider` + `StorIOContentProviderImpl`

@nikitin-da any thoughts?

**Comment by nikitin-da** [comment]
Maybe `StorIODb` + `StorIODbSQLiteImpl` and `StorIOContentProvider` + `StorIOContentProviderImpl`

Too long, but it will be a way more clearly if `SQLite` will be present. 
And we can't get rid from `Impl`, because it is nessesary for content provider.

**Comment by artem-zinnatullin** [comment]
Long :(

But understandable even for those, who see code with `StorIO` for the first time. So, I think it will be okay.

`StorIOCP` instead of `StorIOContentProvider` will be bad, I thought, because `Db` is very common abbreviation for `Database`, but `CP` for `ContentProvider` isn't..

**Comment by artem-zinnatullin** [comment]
Damn, I don't want to see `Impl` in class name, how can we avoid it?

**Comment by nikitin-da** [comment]
`Base` prefix to base class?

**Comment by artem-zinnatullin** [comment]
No, if you'll have `StorIOBaseDb` reference IDE will suggest `storIOBaseDb` field instead of `StorIODb` which is bad :(

**Comment by nikitin-da** [comment]
No, I meant `BaseStorIODb` and `BaseStorIOContentProvider`.

**Comment by artem-zinnatullin** [comment]
`BaseStorIODb` instead of `StorIOSQLiteDb` or instead of `StorIODb`?

**Comment by nikitin-da** [comment]
I thought about `BaseStorIODb` + `StorIODbSQLite` and `BaseStorIOContentProvider' (Oh how long) + `StorIOContentProvider`

**Comment by artem-zinnatullin** [comment]
I'd recommend users to store reference of type `StorIODb` in DI module or somewhere to allow change implementation in future and that reference will be `BaseStorIODb` and will be used as field in many classes and IDE will suggest field name as `baseStorIODb` instead of `storIODb`, pretty ugly :(

**Comment by nikitin-da** [comment]
`AStorIODb` is a bit shortly, but not resolve problem

**Comment by artem-zinnatullin** [comment]
Yeah :(

Seems like `Impl` in implementations is not so bad :smile:
