### ISSUE TITLE
Rename RawQuery.tables

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#141]
`tables` is not very clear name, actually set of tables required for observing changes made by such `RawQuery`.

I suggest to rename `RawQuery.tables` to `RawQuery.affectedTables` so it will be easier to understand that tables won't be binded to SQL query but just declare what tables will be changed by this `RawQuery`

```java
storIODb
  .execSql()
  .withQuery(new RawQuery.Builder()
    .query("ALTER TABLE ? ADD COLUMN ? ? IF NOT EXISTS")
    .args("users", "email", "TEXT")
    .affectedTables("users")
  .prepare()
  .executeAsBlocking();
``` 

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
+1 `affectedTables` 
It's more obvious.

**Comment by artem-zinnatullin** [comment]
:+1:
