### ISSUE TITLE
Divide StorIO to several modules

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#167]
* `StorIOCommon`
* `StorIODb`
* `StorIOContentProvider`
* Possible in future: `StorIORealm`

And we will be able to ship `StorIO` as several jars with minimum classes. Not everybody needs db and content provider at same time

ALSO: May be it's better to rename `StorIODb` to `StorIOSQLiteDb`, because `Realm` is db too

**Comment by nikitin-da** [comment]
Hm, not bad.
