### ISSUE TITLE
API for Realm database

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#169]
Just an issue, all discussions about Realm support should be done here

**Comment by kboyarshinov** [comment]
I finally finished working on update my realm rxjava example to latest Realm version. Fixed threading issues, added multiple subscribers support etc. Probably [`OnSubscribeRealm`](https://github.com/kboyarshinov/realm-rxjava-example/blob/master/app/src/main/java/com/kboyarshinov/realmrxjavaexample/rx/OnSubscribeRealm.java) class can be used as reference to add Realm support to StorIO.

**Comment by artem-zinnatullin** [comment]
@kboyarshinov I'll check this tonight!

**Comment by dadino** [comment]
How would this work? Realm as database and StorIO as Rx interface to access that database?

**Comment by artem-zinnatullin** [comment]
@dadino yes! With all StorIO design principles and features. StorIO is conception with implementations for `SQLiteDatabase` and `ContentResolver`, actually, we're also thinking about JDBC implementation (we need it for our backends).

**Comment by artem-zinnatullin** [comment]
@kboyarshinov I've checked your `OnSubscribeRealm` tonight, it's interesting, though I see few ways to improve it. I think we can discuss StorIORealm this weekends and start work :)

**Comment by kboyarshinov** [comment]
@artem-zinnatullin Cool! I'm in.

**Comment by dadino** [comment]
[Changelog for 0.84](https://github.com/realm/realm-java/blob/master/changelog.txt) reports `Added support for async queries and transactions.`
Could this change the approach @kboyarshinov is using?

**Comment by kboyarshinov** [comment]
@dadino It won't change it. They've added ability to execute quieries async in their own scheduler and queue. Sync methods are the same. These changes won't affect my current implementation.

**Comment by artem-zinnatullin** [comment]
https://github.com/realm/realm-java/pull/1651

**Comment by artem-zinnatullin** [comment]
https://github.com/mulab/rx-realm

**Comment by kboyarshinov** [comment]
@artem-zinnatullin interesting, but I'll stick to wait for native support of RxJava in Realm because all solutions including mine do not fit completely with Realm. Probably we should wait for it too in order to support Realm in StorIO properly.

**Comment by artem-zinnatullin** [comment]
okay, that's fine for me :)

ср, 18 нояб. 2015 г. в 18:51, Kirill Boyarshinov <notifications@github.com>:

> @artem-zinnatullin <https://github.com/artem-zinnatullin> interesting,
> but I'll stick to wait for native support of RxJava in Realm because all
> solutions including mine do not fit completely with Realm. Probably we
> should wait for it too in order to support Realm in StorIO properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/169#issuecomment-157756472>
> .
>
-- 

@artem_zin

**Comment by artem-zinnatullin** [comment]
https://github.com/realm/realm-java/pull/1710

**Comment by kboyarshinov** [comment]
@artem-zinnatullin finally :smile:

**Comment by artem-zinnatullin** [comment]
So, let's close this for now.
