### ISSUE TITLE
Rename affectedTables to changedTables

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#174]
@nikitin-da do you agree?

**Comment by nikitin-da** [comment]
No=) On my opinion, 
`changed`- it is when something took another value, 
but there are cases when value is the same. 
And `affected` that means we became unsure in table immutability.
So, if we will only rename field, without additional checks, it will be more pleasant, but less correctly.

**Comment by artem-zinnatullin** [comment]
Hm, you are right, thank you for opinion :)

вс, 29 марта 2015, 19:13, Dmitrii Nikitin <notifications@github.com>:
