### ISSUE TITLE
Rename StorIOSQLiteDbImpl and StorIOContentProviderImpl

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#195]
Suggestion:

`StorIOSQLiteDbImpl` -> `DefaultStorIOSQLiteDb`
`StorIOContentProviderImpl` -> `DefaultStorIOContentProvider`

Uh, names are so long and ugly :(

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
Did you mean that prefix `Default` will be like a tip to feel free for make custom?

**Comment by artem-zinnatullin** [comment]
Yep,  and it will eliminate "Impl" from class name

ср, 1 апр. 2015, 9:54, Dmitrii Nikitin <notifications@github.com>:

**Comment by nikitin-da** [comment]
Without dagger it will a problem especially auto-generated instance names.
Do you think it is not obvious that they can customize it, and will it be very often then it is necessary to make own implementation.
Or you just want to get ride `impl` suffix?

**Comment by nikitin-da** [comment]
Excuse me for my for my "english"

**Comment by artem-zinnatullin** [comment]
Impl is just bad in class name :)

ср, 1 апр. 2015, 10:27, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
@nikitin-da so, I am doing it?

**Comment by nikitin-da** [comment]
Yes, I don't see another variant

**Comment by artem-zinnatullin** [comment]
Cool

пт, 3 апр. 2015 г. в 0:13, Dmitrii Nikitin <notifications@github.com>:
