### ISSUE TITLE
Fail: StorIOContentProvider should be renamed to StorIOContentResolver

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#197]
Because, actually, `StorIOContentProvider` uses `ContentResolver` and not `ContentProvider`, we even don't specify `ContentProvider's` authority, so it's wrapper for `ContentResolver` only. facepalm.jpg

@nikitin-da PTAL and comment

**Comment by nikitin-da** [comment]
Omg. I have nothing to add.
