### ISSUE TITLE
All Operation Resolvers should construct result of Operation

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#213]
At the moment, all Operations Resolvers returns something like `int`, etc, but `PutResolver`s return `PutResult`.

So, for more unified code style it will be good to make all Operations Resolvers return `OperationResult`.

Also, in future we will be able to make result of some Operation more complex and it will not affect Operation Resolver return type.

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
Using special class for `Delete resolver` result will be definitely better. 
As for me in `Get Resolver` case return something else instead of `cursor` will be less obvious.
But for unification I guess it will be good decision.

**Comment by artem-zinnatullin** [comment]
Oh, for GetResolver I wanted to keep Cursor as result type

вс, 5 апр. 2015, 1:34, Dmitrii Nikitin <notifications@github.com>:
