### ISSUE TITLE
Compile checkable required params for all builders

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#218]
I really don't like that our builders can be used incorrectly and if user would forget required param he will see this only in runtime, and it will be crash or the application..

We can make incorrect usage of builders non-compilable, there is workaround for this via interfaces: http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

@nikitin-da do you agree?

**Comment by artem-zinnatullin** [comment]
Another link: http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

**Comment by nikitin-da** [comment]
For our case it is just right. Can I take it?

**Comment by artem-zinnatullin** [comment]
Yes, will be great! Can you start with PR for one Builder? I'd like to see how it will be done :)

**Comment by nikitin-da** [comment]
Yep

**Comment by artem-zinnatullin** [comment]
Cool

вс, 5 апр. 2015 г. в 23:55, Dmitrii Nikitin <notifications@github.com>:

**Comment by nikitin-da** [comment]
Did you talk about another link?=) 
It was the same (http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java)

**Comment by artem-zinnatullin** [comment]
Lol, my fault, here is another link: http://www.jayway.com/2012/02/07/builder-pattern-with-a-twist/

Or just Google it: `java builder pattern required parameters`

**Comment by artem-zinnatullin** [comment]
I don't remember, but this problem may also be covered in `Effective Java`

**Comment by nikitin-da** [comment]
Thanks
Hm, I don't remember it in this book

**Comment by artem-zinnatullin** [comment]
Just linking PRs here, @nikitin-da please write something like `refs #218` or `part of #218` in PRs  for that issue, it'll be easier to see, what's already done

Refs: #246, #245, #233, #231, #230, #229, #226

**Comment by nikitin-da** [comment]
ok, thank you

2015-04-09 21:35 GMT+03:00 Artem Zinnatullin <notifications@github.com>:
