### ISSUE TITLE
Rename StorIOSQLiteDb

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#222]
What about `StorIOSQLite`?

`SQLite` is already Database, there is no real need to write `SQLiteDb`

Shorter names -> better API.

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
+

**Comment by nikitin-da** [comment]
It's nice change

**Comment by artem-zinnatullin** [comment]
Glad to read that! I hate Enterprise-like class names..

**Comment by artem-zinnatullin** [comment]
@nikitin-da I am on it, please wait if you're doing other PRs, it'll be hard to merge our conflicts
