### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#257]
Issue to discuss upcoming release `1.0.0`

**Comment by artem-zinnatullin** [comment]
UPD: I had created issue in Sonatype's Jira for `StorIO`

https://issues.sonatype.org/browse/OSSRH-14941

**Comment by nikitin-da** [comment]
How much time does it usually takes?

**Comment by artem-zinnatullin** [comment]
Several days

сб, 11 апр. 2015, 16:01, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
Sonatype gave `com.pushtorefresh` for us, now we can deploy any artifacts and subgroups like `com.pushtorefresh.storio:sqlite` and so on!

Current blockers for  v1.0.0: `Operations Resolvers` refactoring + integration tests for `StorIOContentResolver`

**Comment by nikitin-da** [comment]
Cool news!

2015-04-13 17:50 GMT+03:00 Artem Zinnatullin <notifications@github.com>:

**Comment by gabrielittner** [comment]
Could you publish snapshots until the release? I would like to try it out and that would make it much easier.

**Comment by artem-zinnatullin** [comment]
That would be great, but it'll take some time to configure publishing, at the moment I can suggest you to clone and build it `sh ci/ci.sh`

I created an issue for that #299

**Comment by PiXeL16** [comment]
Nice, any news on the release?

**Comment by artem-zinnatullin** [comment]
Yep, I am going to work hard on StorIO next week and I think we'll release RC-1 to Maven Central ASAP.

Stay tuned!

**Comment by PiXeL16** [comment]
Thanks!

**Comment by atomd** [comment]
Waiting for the release!

**Comment by artem-zinnatullin** [comment]
Me too! :) WIP, we have some problems with CI and one API design thing

**Comment by ilya-murzinov** [comment]
Hi guys!
Need any help? :)

**Comment by artem-zinnatullin** [comment]
Yo! Glad to see you here, Ilya!

I think, we've covered most things, I'm currently finishing API design things and resolving CI problems.

Would be great if you'd take a look at new PRs, we won't block them without your feedback, but if you would see something bad -> please comment it!

**Comment by ilya-murzinov** [comment]
It's a nice project you have here, so I thought, why not? :)
I'll try just to take a closer look to begin with.

**Comment by artem-zinnatullin** [comment]
Looks like we are good to go! Hope I didn't miss anything.

**Comment by artem-zinnatullin** [comment]
Good news everyone! I've successfully uploaded `0.9.1-SNAPSHOT` to Maven Central, just for testing upload configuration.

@nikitin-da hope you'll review and merge remaining PRs and I'll publish `1.0.0-SNAPSHOT`, we will play couple days with it and I'll release final `1.0.0`!

Also, I'll probably set up auto-uploading for SNAPSHOTS.
