### ISSUE TITLE
Default Mapping and Resolvers

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#274]
Setting `MapFunc` and `Resolvers` for each Operation is pretty annoying 

We can allow user to set default `MapFunc`'s and `Resolvers` for `StorIOSQLite` and `StorIOContentResolver` and allow to override them per Operation. 

@nikitin-da what do you think?

**Comment by artem-zinnatullin** [comment]
My vision for `StorIOSQLite`:

`DefaultStorIOSQLite` should allow set `SQLiteType` mapping in builder

```java
SQLiteTypeMapping<User> userTypeMapping = new SQLiteTypeMapping.Builder()
  .type(User.class)
  .mappingToContentValues(User.MAP_TO_CONTENT_VALUES)
  .mappingFromContentValues(USER.MAP_FROM_CONTENT_VALUES)
  .mappingToInsertQuery(User.MAP_TO_INSERT_QUERY)
  .mappingToUpdateQuery(User.MAP_TO_UPDATE_QUERY)
  .mappingToDeleteQuery(User.MAP_TO_DELETE_QUERY)
  .build();

...

StorIOSQLite storIOSQLite = new DefaultStorIOSQLite.Builder()
  .db(db)
  .addTypeMapping(userTypeMapping)
  .addTypeMapping(tweetTypeMapping)
  .build();
```

And Operation Builders will try to get type mapping from `StorIOSQLite.internal().typeMapping(User.class)` like this or allow to override default mapping per Operation

```java
storIOSQLite
  .get()
  .listOfObjects(User.class)
  .query(User.QUERY_ALL)
  .prepare()
  .executeAsBlocking();

storIOSQLite
  .put()
  .object(newUser)
  .prepare()
  .executeAsBlocking();

storIOSQLite
  .delete()
  .objects(oldUsers)
  .prepare()
  .executeAsBlocking();
```

And similar implementation for `StorIOContentResolver`.

It'll make using of `StorIO` better, btw in future we can add something like `AutoTypeMapping` and resolve mapping via reflection + annotations or via annotations + compile time processor

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
Absolutely agree, it'll be much convenient to use, because on the one hand separate setting `MapFunc` and `Resolvers` gives more flexibility, but on the other hand it is far non common case, when it is really need. So, requirement to set `some resolvers` twice may be scary for users that accustomed to make serialization via annotations.

**Comment by artem-zinnatullin** [comment]
Okay, I'll prepare PR for that

сб, 11 апр. 2015, 16:11, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
@nikitin-da current implementation is not consistent :(

It asks for:

* `mappingToContentValues`
* `mappingFromCursor` // GetResolver
* `putResolver` // mapping to InsertQuery and UpdateQuery
* `mappingToDeleteQuery` // DeleteResolver

May be we should ask only for Resolvers or only for Queries? I think Resolver will be better, because with current implementation you can not store one Java object in several tables: you can override `PutResolver` (accepts ContentValues), but you can't properly override `DeleteResolver` (accepts `DeleteQuery`).

Also, I don't like that `PutResolver` accepts `ContentValues`, while `GetResolver` and `DeleteResolver` accept `Queries`, no consistency :(

**Comment by nikitin-da** [comment]
Do you think we need to provide only resolvers, that will accept `content values`?

**Comment by artem-zinnatullin** [comment]
I see several variants:

1. Resolver should accept `object of some type`

Put Operation:
```java
public class PutResolver<T> {

  public PutResult performPut(StorIOSQLite storIOSQLite, T object) {
    // insert or update
  }
}

public abstract class DefaultPutResolver<T> extends PutResolver<T> {
  
  protected abstract InsertQuery provideInsertQuery(T object);

  protected abstract UpdateQuery provideUpdateQuery(T object);

  // faster than returning MapFunc<T, ContentValues> and calling mapFunc.map(object)
  protected abstract ContentValues mapToContentValues(T object);

  public PutResult performPut(StorIOSQLite storIOSQLite, T object) {
    UpdateQuery updateQuery = provideUpdateQuery(t);

    if (storIOSQLite.internal().get(new Query.Builder()
      .table(updateQuery.table)
      .where(updateQuery.where)
      .whereArgs(updateQuery.whereArgs)
      .build())
      == 0) {  // if no such records -> insert
         storIOSQLite.internal().insert(provideInsertQuery(t), mapToContentValues(t));
     } else { // if records exist -> update
         storIOSQLite.internal().update(updateQuery, mapToContentValues(t));
     }
  }
}
```

Get Operation:

```java
public abstract class GetResolver<T> {

  // will be called from Get Operation, not from Resolver impl  
  public abstract MapFunc<Cursor, T> provideMapFunc();  

  public abstract Cursor performGet(StorIOSQLite storIOSQLite, Query query);

  public abstract Cursor performGet(StorIOSQLite storIOSQLite, RawQuery rawQuery);
}


public class DefaultGetResolver<T> extends GetResolver<T> {
  
  // user has to provide only MapFunc<Cursor, T>

  public Cursor performGet(StorIOSQLite storIOSQLite, Query query) {
    return storIOSQLite.internal().query(query);
  }

  public Cursor performGet(StorIOSQLite storIOSQLite, Raw rawQuery) {
    return storIOSQLite.internal().query(rawQuery);
  }
}
```

Delete Operation:

```java
public abstract class DeleteResolver<T> {

  public abstract DeleteResult performDelete(StorIOSQLite storIOSQLite, T object);

}

public abstract class DefaultDeleteResolver<T> extends DeleteResolver<T> {
  
  public abstract DeleteQuery mapToDeleteQuery(T object);

  public DeleteResult performDelete(StorIOSQLite storIOSQLite, T object) {
    return DeleteResult.newInstance(storIOSQLite.internal().delete(mapToDeleteQuery(object)));
  }
}
```


Prons:

* Requires only three resolvers per type
* Object of one type can be stored in several tables with custom Resolvers and all Operations will be able to work with it, current implementation can not offer this


Cons:

* RawQuery with join will require not `MapFunc<Cursor, Object>`, but `GetResolver`
* MapFunc not used in most of things, it was pretty simple and understandable

**Comment by artem-zinnatullin** [comment]
Second variant: Require:

* `MapFunc<T, ContentValues>`
* `MapFunc<Cursor, T>`
* `MapFunc<T, InsertQuery>`
* `MapFunc<T, UpdateQuery>`
* `MapFunc<T, DeleteQuery>`

And default resolvers from `StorIO` will work for most cases.

Prons:

* `MapFunc` for everything
* `Resolvers` are not required at all, we can safely remove them from `StorIO`
* `RawQuery` with `JOIN` can be easily mapped to custom object via overriding `MapFunc` for Get Operation

Cons:

* You can not save one object to multiple tables, no way to do this via `StorIO`, but I don't think that storing one object in multiple tables is really common
*  Custom resolvers won't be able to really customize something because they will receive ContentValues and already built Queries
* Put Operation will be less effective than with 1 variant, because it'll require already built `InsertQuery` and `UpdateQuery`, but only one of them will be used
* No way to make something like `afterPut(PutResult putResult, T object)`
