### ISSUE TITLE
Write about Hot and Cold Observables

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#281]

**Comment by nikitin-da** [comment]
Hm, what is it?

**Comment by artem-zinnatullin** [comment]
Different types of `rx.Observables`, I can tell you about them later, http://stackoverflow.com/questions/2521277/what-are-the-hot-and-cold-observables

In shorts:

Cold Observable — Observable that won't emit items while Observer won't subscribe to it, so Observer won't loose any items in normal situation.

Hot Observable — Observable that emits items even if there are NO Observers, so Observer can miss some items.

**Comment by nikitin-da** [comment]
Ok, thank you

2015-04-14 13:08 GMT+03:00 Artem Zinnatullin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
Fixed by #336 and #340.
