### ISSUE TITLE
Option for Get Operation to return ImmutableList

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#289]
It can be useful for reusing result of Get Operation `Observable` with `replay()` and same operators

**Comment by artem-zinnatullin** [comment]
I am closing this at the moment.

If user's classes are mutable, immutable list wouldn't do too much.

With RxJava user can easily map result to immutable list:

```java
storIOSQLite
  .get()
  .listOfObjects(Tweet.class)
  .withQuery(...)
  .prepare()
  .createObservable()
  .map(listOfTweets -> Collections.immutableList(listOfTweets))
```

**Comment by nikitin-da** [comment]
Ok
