### ISSUE TITLE
Integration tests for createObservableStream() and observeChanges()

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#295]
@nikitin-da can you write integration tests for that?

I hope you'll like `RxJava` :)

**Comment by nikitin-da** [comment]
Yep!

**Comment by artem-zinnatullin** [comment]
@nikitin-da any estimation on this? RxJava is waiting for you :)

**Comment by nikitin-da** [comment]
Sorry, I hope 2 days.

**Comment by artem-zinnatullin** [comment]
No problems, just asking :)

сб, 25 апр. 2015, 20:58, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
Done!
