### ISSUE TITLE
Remove createObservableStream()

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#315]
I think, RxJava support should be 100% reactive, that means that such code

```java
storIOSQLite
  .get()
  .listOfObjects(Tweet.class)
  .withQuery(new Query.Builder()
    .table("tweets")
    .build())
  .prepare()
  .createObservable()
  .subscribeOn(Schedulers.io())
  .observeOn(AndroidSchedulers.mainThred())
  .subscribe(tweets -> {
    // this should be reactive stream
    // each change should reload it
  });
```

`createObservableStream()` is not a good name, because `Observable` is `stream` by its nature.

If user needs to get result one time, he should use `observable.take(1)`

@nikitin-da PTAL and write your opinion please

**Comment by nikitin-da** [comment]
I guess, #77 also was created for this problem. I think yes, it should be obivios, that if you use `createObservable` for operation, you just subscribe only to it. Not to all changes in table.

**Comment by artem-zinnatullin** [comment]
Wait wait wait :)

Please reread issue carefully, I want to remove `createObservableStream()` and leave only `createObservable()` which will be subscribed to changes in tables from query.

It will make API more convenient and really reactive
