### ISSUE TITLE
Callback execution model

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#317]
Currently, `StorIO` provides 2 execution models:

 * `executeAsBlocking()`
 * `createObservable()`

If somebody needs it -> please comment with "+1", so we will know that it should be implemented

**Comment by Rainer-Lang** [comment]
Im thinking to switch from an orm lib to storio - but I don't know want I need. Please add as much as you can, so storio-community and tester can grow.

Please explain executeAsBlocking() (transaction?) and what createObservable() will do.
Thanks.

**Comment by artem-zinnatullin** [comment]
`executeAsBlocking()` will execute some operation as blocking synchonous call in current thread, it does not related to transactions (which are supported for group Put and Delete Operations).

`createObservable()` will create `rx.Observable`, it's part of RxJava project https://github.com/ReactiveX/RxJava

So at the moment StorIO supports two execution models: execution as blocking call and execution as `rx.Observable`, we can add callback-oriented execution model in future.

**Comment by artem-zinnatullin** [comment]
Closing for now, anybody interested in this — feel free to comment.
