### ISSUE TITLE
ExecuteSQL Operation does not send notifications

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#339]
ExecSQL Operation should send notifications about changes if `RawQuery` contains `affectedTables`.

**Comment by nikitin-da** [comment]
Do we need to parse query to detect affected tables?

**Comment by artem-zinnatullin** [comment]
Yes.

пн, 18 мая 2015, 8:51, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
> Do we need to parse query to detect affected tables?

Oh, I didn't get it at the first time, so the real answer is "No."

We have `RawQuery#affectsTables()`
