### ISSUE TITLE
Best approach when working with existing SQLite database

### ISSUE THREAD

**Issue by PiXeL16** [pushtorefresh/storio#343]
Hi, 
Was just wondering if there is a suggested approach when working with a existing data with storio?
I will like to ship my app with a lot of existing data. Should I copy my .db from assets to db folder in first launch or is there anything better I can do? 
Thanks!

**Comment by artem-zinnatullin** [comment]
Hello!
Can you please ask this question on StackOverflow and post link here (I'll answer there)? 

We would like to keep GitHub issues for bug reports and feature requests only, questions about usage patterns, etc can be asked on StackOverflow, nothing personal :)

Thanks!

**Comment by PiXeL16** [comment]
Sure thing, sorry about that.
http://stackoverflow.com/questions/30309915/best-approach-when-working-with-existing-sqlite-database-in-storio

**Comment by artem-zinnatullin** [comment]
Answered! Feel free to ask more/comment the answer!
