### ISSUE TITLE
Kill nulls in Queries!

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#346]
Nulls everywhere in StorIO, that's good for performance, but not safe for users, I think that it's better to lose 1% of performance, but provide safety instead.

**Comment by nikitin-da** [comment]
Do you mean use final collections with `addAll` instead of assignment or something else?

**Comment by artem-zinnatullin** [comment]
Nope, I mean `null`s in Queries and other classes

```java
RawQuery rawQuery = new RawQuery.Builder()
  .query("SELECT * FROM tweets")
  .build();

rawQuery.args() == null; // -> true
rawQuery.observesTables() == null; //-> true
rawQuery.affectsTables() == null; // -> true
```
