### ISSUE TITLE
Documentation: Add example of getting result once via Get Operation as rx.Observable

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#353]

**Comment by nikitin-da** [comment]
Is it actual?

**Comment by artem-zinnatullin** [comment]
Yes!
21 июня 2015 г. 10:06 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Comment by artem-zinnatullin** [comment]
@nikitin-da if you have time, I'll be happy to review your PR for this issue

**Comment by nikitin-da** [comment]
Ok, I'll do it this evening.

**Comment by artem-zinnatullin** [comment]
Done!
