### ISSUE TITLE
Use threading annotations from Support-Annotations 22.2.0

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#361]
We can mark some methods with new `@MainThread` and `@WorkerThread` annotations http://tools.android.com/tech-docs/support-annotations

**Comment by nikitin-da** [comment]
Wow. Awesome novelity =)

**Comment by artem-zinnatullin** [comment]
Yup!
4 июня 2015 г. 10:49 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:
