### ISSUE TITLE
Type mapping with AutoValue/AutoParcel

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#365]
Link to discussion on reddit: https://www.reddit.com/r/androiddev/comments/38nx2t/weekly_anything_goes_thread/crxm900

The problem:

`SQLiteTypeMapping` and `ContentResolverTypeMapping` store pairs for type mapping with exact class, for example: `[(Tweet.class, TweetPutResolver), (Tweet.class, TweetGetResolver)...]`.

But with `AutoValue` and `AutoParcel` it won't resolve required class.

> There was one hiccup with AutoParcel and SQLiteTypeMapping. AutoParcel generates child class for every annotated class, but it's package private and can't be used when creating type mapping but type mapping created using parent class doesn't work with child object since prepare operation uses getClass to find appropriate type mapping. For example:

```java
@AutoParcel
public abstract class Foo {
    abstract int id();
    abstract String bar();
    public static Foo create(int id, String bar) {
        return new AutoParcel_Foo(id, name);
}

StorIOSQLite storIOSQLite = new DefaultStorIOSQLite.Builder()
.sqliteOpenHelper(helper)
.addTypeMapping(Foo.class, new SQLiteTypeMapping.Builder<Foo>()
    .putResolver(new FooPutResolver())
    .getResolver(new FooGetResolver())
    .deleteResolver(new FooDeleteResolver())
    .build())
.build();

Foo foo = Foo.create(0, "baz"); // foo.getClass returns AutoValue_Foo

storIOSQLite
  .put()
  .object(foo)
  .prepare() // prepare can't find mapping for AutoValue_Foo
  .executeAsBlocking() 
```

> On user side it can be solved by specifying concrete right resolver for every operation or using generated class type in type mapping and resolver declaration neither of which very flexible. How it can be solved in library I have no idea. So for now I stopped using AutoValue for db entity objects (same with Gson based entities since AutoValue doesn't play nice with it either).

**Comment by artem-zinnatullin** [comment]
I made two solutions:

1 TypeMapping can store synonym classes

```java
addTypeMapping(Foo.class, new SQLiteTypeMapping.Builder<Foo>()
    .putResolver(new FooPutResolver())
    .getResolver(new FooGetResolver())
    .deleteResolver(new FooDeleteResolver())
    .addSynonymClass(AutoParcel_Foo.class)
    .build())
```

And StorIO will use resolvers of `Foo.class` for `Foo.class` itself and for all its synonyms.

2 Use `Class.isAssignableFrom()` and check that passed class has mapping for its parent class, no user action required.

And, I decided to implement 2nd solution, because it's pretty cheap for performance (I made caching) and it's easy for users. Works with `@AutoParcel` like a charm.

**Comment by nikitin-da** [comment]
Cool! But I guess with second solution we can meet a little problem.
What if we have hierarchy of classes and use `@AutoParcel`.
For example: `User <|-- UserDetails`.
So `User <|-- AutoParcel_User` and `UserDetails <|-- AutoParcel_UserDetails`
And try to add different type mapping for it:
`addTypeMapping(User.class, new SQLiteTypeMapping.Builder<User>()
    .getResolver(new UserGetResolver())
    .build())`
and
`addTypeMapping(UserDetails.class, new SQLiteTypeMapping.Builder<UserDetails>()
    .getResolver(new UserDetailsGetResolver())
    .build())`
Auto parcel for both classes `User` and `UserDeatails` will not have direct type mapping, and when we will search indirect one for `UserDetails`, we can firstly meet `User` type mapping  (`typeWithMapping.isAssignableFrom(type)` will return true =( )
I.e. it depends on luck what we will meet firstly in 
`for (Class<?> typeWithMapping) typesMapping.keySet())` loop.

**Comment by artem-zinnatullin** [comment]
Damn, you're right...
8 июня 2015 г. 9:19 AM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Comment by artem-zinnatullin** [comment]
Okay, I can solve this, but it'll be liiitle slower, just a little for most of the cases. I'll count "how many classes between these two in the inheritance relation" and then I'll choose most closer class with known type mapping.

**Comment by nikitin-da** [comment]
Maybe with caching it will be ok

**Comment by artem-zinnatullin** [comment]
Yep
8 июня 2015 г. 10:48 AM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:
