### ISSUE TITLE
Execute SQL Operation should not return null

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#366]
It breaks contract of `PreparedOperation`.

**Comment by BraunreutherA** [comment]
Hey there,

it seams that its still possible to get null as result:

```java 
storIOSQLite
                .get()
                .object(TextMessageEntity.class)
                .withQuery(TextMessageTable.QUERY_ALL)
                .prepare()
                .createObservable()
                .map(textMessageEntity -> {
                    Log.d("TAG", textMessageEntity.toString()); // textMessageEntity is null
                    return textMessageDataMapper.transform(textMessageEntity);
                });
```

Am I doing something wrong or why is it null?

**Comment by nikitin-da** [comment]
Hi @BraunreutherA 
This issue relates just to raw sql query. I think, `null` is the most expected when we request nonexistent object (`executeAsBlocking` [for this case](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/get/PreparedGetObject.java) is still `nullable`).
@artem-zinnatullin to make it fairly, should we mark base method as `nullable`?

**Comment by artem-zinnatullin** [comment]
>to make it fairly, should we mark base method as nullable

Well… Yes, let's do it.

@BraunreutherA it's expected behavior since object with required query params may not exist in the db, for example `get().listOfObjects()` will return empty list in such case.

**Comment by BraunreutherA** [comment]
Okay, that makes sense. I was confused cause it was marked as a non-null method. Thanks for the explanation!

**Comment by artem-zinnatullin** [comment]
@BraunreutherA yeah, sorry, my bad!

Hope you're enjoying the library :)
