### ISSUE TITLE
Fix content resolver integration test: manually call contentObserver

### ISSUE THREAD

**Issue by nikitin-da** [pushtorefresh/storio#375]

**Comment by artem-zinnatullin** [comment]
Or we can create ContentProvider in the sample app and move integration
tests for ContentResolver inside of the sample app
8 июня 2015 г. 9:41 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:

**Comment by artem-zinnatullin** [comment]
Or we can use Robolectric (but I am not big fan of it).

**Comment by artem-zinnatullin** [comment]
@nikitin-da do you have any estimation on this? At the moment, it's the only real blocker of 1.0.0

**Comment by nikitin-da** [comment]
Yes, I will move it to sample app this evening.

**Comment by artem-zinnatullin** [comment]
Great, thanks!

**Comment by artem-zinnatullin** [comment]
Closed by #383.
