### ISSUE TITLE
Create builders via static methods

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#382]
IntelliJ IDEA's suggestions engine doesn't handle `new Something.Builder()` properly, it always suggests me `new Something()` instead of builder even if constructor of `Something` is `private`.

So, I think we should switch to `Something.builder()`, it also requires less symbols in compare to `new Something.Builder()`.

**Comment by nikitin-da** [comment]
Сan I take it?

**Comment by artem-zinnatullin** [comment]
Sure, let's do it!
14 июня 2015 г. 9:50 PM пользователь "Dmitrii Nikitin" <
notifications@github.com> написал:
