### ISSUE TITLE
Packages naming policy: Switch from Singular to Plural

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#412]
Hope it's last issue before `1.0.0`.

**Package naming policy:**

http://programmers.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural

Currently we have "Singular" variant of packages naming, for example: `com.pushtorefresh.stroio.sqlite.operation`, but in fact it contains several Operations and it'll be more correctly to name it `com.pushtorefresh.stroio.sqlite.operations`.

Also, we will have more cool artifact for `sqlite-annotations`:

Before: `compile 'com.pushtorefresh.storio:sqlite-annotation:+'`
After: `compile 'com.pushtorefresh.storio:sqlite-annotations:+' // in fact, there are several annotations`

@nikitin-da your thoughts?

**Comment by nikitin-da** [comment]
Matthew Rodatus is convincing. I completely agree.
