### ISSUE TITLE
Provide public API to ChangesBus to allow users subscribe to all changes in StorIO

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#446]
At the moment user can observe changes of particular tables (in `StorIOSQLite`) or particular `Uris` (in `StorIOContentResolver`).

I think it could be useful for users (at least for me and our current work project) to have an API that will allow to observe all changes without filtration, for example for logging and other purposes.

@nikitin-da thoughts? I remember that we discussed this several months ago and decided to provide only `observeChanges(tables)` and `observeChanges(uris)` to prevent users from EventBus-like code, but now I see usages for general `observeChanges()` API.

**Comment by nikitin-da** [comment]
Just for logging? Do you have other ideas why it may be helpful, listen entire db regardless of the tables?

**Comment by artem-zinnatullin** [comment]
You can dynamically decide what to filter and yes -> logging, but we will provide logging in some future release…

**Comment by Rainer-Lang** [comment]
Logging is essential.
Very nice - I'm looking forward.

For now I'm using DBFlow, but storio is getting better and better - and for me it's important that I can use rxjava.

**Comment by artem-zinnatullin** [comment]
Sure, logging is essential but we'll provide it as separate feature #79.
