### ISSUE TITLE
Add recipe of taking one result via RxJava 

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#452]
Actually, it's just like:

```java
storIOSQLite
  .get()
  .listOfObjects(User.class)
  .withQuery(...)
  .prepare()
  .createObservable()
  .take(1) // Operator Take will take one result and unsubscribe from the root observable
  .observeOn(mainThread())
  .subscribe(users -> { ... });
```

**Comment by plastiv** [comment]
return `rx.Single` to clarify API contract? https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#rxsingle

**Comment by artem-zinnatullin** [comment]
I'd like to use it, but 1 - it's experimental API in RxJava 1.0.13, 2 -
how can we integrate it into PreparedOperation?
21 июля 2015 г. 12:00 PM пользователь "Sergii Pechenizkyi" <
notifications@github.com> написал:

**Comment by artem-zinnatullin** [comment]
@plastiv, @geralt-encore has implemented `rx.Single` support, we'll release it as part of StorIO 1.8.0!
