### ISSUE TITLE
Remove Query.whereArgs(List<?> whereArgs) from StorIOSQLite

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#457]
This was my mistake in the API, I guess, nobody used it because we have nice overload which is used in all other Queries `whereArgs(Object… whereArgs)`.

I think it's okay to remove this API in 1.1.0?

@nikitin-da, anybody?

**Comment by nikitin-da** [comment]
I agree. But have you decided that it will not break compatibility?

**Comment by artem-zinnatullin** [comment]
Unfortunately it will break compatibility, but I hope nobody uses it because there is `Object... whereArgs` overload.

Recently OkHttp denied body in PUT and DELETE requests, I didn't see so many issues about one change for a while…

I think it's critical to made this change ASAP while we don't have a lot of users.

**Comment by nikitin-da** [comment]
Ok. Lets remove it.

**Comment by artem-zinnatullin** [comment]
Reopening, this is incompatible API change, so we need to move this issue to v2.0.0

PR with revert — #468

**Comment by vokilam** [comment]
@artem-zinnatullin, @nikitin-da, before removing `whereArgs(List<?> whereArgs)` consider more complex cases of constructing a query. In example below, additional expressions are appended to where clause based on condition. One would probably implement it like this:

    boolean includeHappyTeenagers = true;
    StringBuilder whereBuilder = new StringBuilder();
    List<Object> argsList = new ArrayList<>();

    // required part
    whereBuilder.append("age BETWEEN ? AND ?");
    argsList.add(60);
    argsList.add(90);

    // optional part
    if (includeHappyTeenagers) {
        whereBuilder.append(" OR age BETWEEN ? AND ? AND mood > ?");
        argsList.add(13);
        argsList.add(18);
        argsList.add(0.7);
    }

    Cursor c = db.get().cursor()
            .withQuery(Query.builder()
                            .table("people")
                            .where(whereBuilder.toString())
                            .whereArgs(argsList)
                            .build()
            )
            .prepare()
            .executeAsBlocking();

    c.getCount();
    c.close();

Without `whereArgs(List<?> whereArgs)` same result will be possible to achieve by converting to a plain array:

    whereArgs(argsList.toArray())
    whereArgs(argsList.toArray(new Object[argsList.size()]))

that doesn't look beautiful.
Moreover, developer might mistakenly think that `whereArgs(Object... whereArgs)` accepts `List<?>` object, then he would write perfectly valid `whereArgs(argsList)` and would get the following result:

    SELECT * FROM people 
    WHERE age BETWEEN '[60, 90, 13, 18, 0.7]' AND NULL 
      OR age BETWEEN NULL AND NULL AND mood > NULL

because every array item from `Object... whereArgs` argument is converted to its string representation.
This problem is actual for `RawQuery.args(Object... args)` also. Raw queries may be used for much more complex queries, e.g. unions.

To my mind, `whereArgs(List<?> whereArgs)` should exist both in `Query` and `RawQuery`. Guys, what are your thoughts on this case? How to construct complex queries with less pain?

**Comment by artem-zinnatullin** [comment]
In general, I agree with you, the only thing that I don't like is keeping both `Object...` and `List` overloads, because it looks suspicious both for the compiler and me.

I'll check what we can do here and probably add it to the `RawQuery` too.

@vokilam, thanks for the input!

**Comment by mipreamble** [comment]
@artem-zinnatullin 

where should append to the previous selection rather than replacing the existing clause

public Builder where(String selection, String... selectionArgs) {
        if (TextUtils.isEmpty(selection)) {
            if (selectionArgs != null && selectionArgs.length > 0) {
                throw new IllegalArgumentException(
                        "Valid selection required when including arguments=");
            }

            // Shortcut when clause is empty
            return this;
        }

        if (mSelection.length() > 0) {
            mSelection.append(" AND ");
        }

        mSelection.append("(").append(selection).append(")");
        if (selectionArgs != null) {
            Collections.addAll(mSelectionArgs, selectionArgs);
        }

        return this;
    }

thoughts ?

**Comment by artem-zinnatullin** [comment]
>where should append to the previous selection rather than replacing the existing clause

We've discussed this with @nikitin-da and decided to keep current behavior. The main reason for this is that it will be non-intuitive for the users of the library, because all other methods of the Query builder won't do this, for example: `sortOrder()`, `limit()` and  so on. Also, it'll require kind of understanding of the SQL inside of StorIO (you're adding ` AND ` between two `where()`) which we are trying to avoid. Sorry for this, but I hope you'll find our decision pretty reasonable and good :)

>Also a toBuilder() method to edit the existing Query will be nice.

YES! I want this too, created issue for this #537 (planned for v1.6.0).

**Comment by mipreamble** [comment]
@artem-zinnatullin 

1. I understand. I wrote a little wrapper around for myself for all my entities. Sample below.
Makes it easier for me to create Queries and pass them.

```java
public static class TweetQuery {

        final Query.CompleteBuilder builder = Query.builder().table(TweetsTable.TABLE);
        StringBuilder selection = new StringBuilder();

        public TweetQuery() {
        }
        
       // Similarly or and between addition.
        private void and(String where, String... whereArg) {
            if (selection.length() > 0) {
                selection.append(" AND ");
            }
            selection.append(where).append(" = ").append(whereArg);
        }

        public TweetQuery id(Long id) {
            and(TweetsTable.COLUMN_ID, String.valueOf(id));
            return this;
        }

        public TweetQuery author(String author) {
            and(TweetsTable.COLUMN_AUTHOR, author);
            return this;
        }

        public Query.CompleteBuilder build() {
            return builder
                    .where(selection.toString());
        }
    }
```

2. Cool.

**Comment by artem-zinnatullin** [comment]
1. Nice!
2. We'll try to ship it :ship: soon!

**Comment by gbero** [comment]
Correct me if I'm wrong but doing : 

selection.append(where).append(" = ").append(whereArg);

will prevent indexes from being used no ?

**Comment by artem-zinnatullin** [comment]
Should work okay, indexes will be applied after all placeholders will be processed and changed with real values.

**Comment by artem-zinnatullin** [comment]
@nikitin-da @geralt-encore what should we do with this?

**Comment by nikitin-da** [comment]
maybe remove this method before v2 or v3?

**Comment by Rainer-Lang** [comment]
Does removing this method will help users? If not - better keep it. 
On the other hand, are there technical problems with keeping it?

**Comment by nikitin-da** [comment]
@Rainer-Lang, there is no technical problem. But as @artem-zinnatullin said above it looks 
 suspicious for compiler=(
Moreover it looks inconsistent because other queries do not contain for now overload that takes list (ContentResolver: query, deleteQuery, updateQuery. Sqlite: deleteQuery, updateQuery and rawQuery)
Btw observesTags and affectsTags have both variant

**Comment by geralt-encore** [comment]
+1 for removing it. It is a rare chance to clean up the API :)
