### ISSUE TITLE
Feature request: create / drop table API for Humans

### ISSUE THREAD

**Issue by dmytrodanylyk** [pushtorefresh/storio#471]
As I see in sample you are using [string concatenation](https://github.com/pushtorefresh/storio/blob/master/storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/db/DbOpenHelper.java#L19-L25) for create table query. Maybe storio need create / drop table query builder for Humans ? :)

**Comment by artem-zinnatullin** [comment]
Current position about this: `StorIO` is API for querying (Put, Get, Delete) DB and `ContentResolver`. We don't want to limit our users in creating and managing their databases, tables, constraints, schemas and so on :)

Also, we won't provide SQL generation.

Sorry if it makes you less happy, but we think that good library should do as little work as possible and respect SOLID principles (in particular Single Responsibility).

We like to manually manage our database schemas, via quick googling I've found this library which can help you with managing database schema: https://github.com/futuresimple/android-schema-utils

**Comment by dmytrodanylyk** [comment]
@artem-zinnatullin ok, fair enough.
