### ISSUE TITLE
How about performance? 

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#487]
Sample Tweets app isn't really fast on my nexus 5. 
The tweets aren't much data. Maybe it's possible to show better performance with more realistic data.

**Comment by artem-zinnatullin** [comment]
There is delay in the sample app, take a look in the code :) Just remove to see how fast is it for real :)

**Comment by Rainer-Lang** [comment]
Ok. Just a proposal: in the sample app - let the user decide to load with and without delay. The sample app is to show what storio can.... To slow it down - is this someting you really want? ;-) 
If storio is fast - show it! :-)

**Comment by artem-zinnatullin** [comment]
Okay, let's remove the delay :)
