### ISSUE TITLE
@StorIOSQLiteColumn(...)

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#493]
For now this is needed:
```java
@StorIOSQLiteColumn(name = "colName")
public Long colName;
```

If annotated column name is same as the attribute name, would this be possible (in future):
```java
@StorIOSQLiteColumn
public Long colName;
```

**Comment by artem-zinnatullin** [comment]
Personally, I'd prefer explicit column name, because you may use proguard or other obfuscation which will rename this field and app will crash in runtime.

@nikitin-da your opinion?

**Comment by Rainer-Lang** [comment]
OK - thanks Artem. I haven't thought about Proguard, but I want to use it in future....
So, for me this issue could be closed.

**Comment by artem-zinnatullin** [comment]
Great :)
