### ISSUE TITLE
Can't compile anymore with newest commit.

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#499]

**Comment by Rainer-Lang** [comment]
Checked-out another commit and compile - all fine.
Rechecked-out latest commit and compile - no error anymore. 

-> all is fine => closing issue.

**Comment by artem-zinnatullin** [comment]
In such situations you can try to do clean build without caches :)

**Comment by Rainer-Lang** [comment]
OK - thanks Artem.
