### ISSUE TITLE
Error:Execution failed for task ':app:packageDebug'. --- Duplicate files copied in APK

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#502]
Error:Execution failed for task ':app:packageDebug'.

Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor

File 1: abc\.gradle\caches\modules-2\files-2.1\com.google.auto.service\auto-service\1.0-rc2\51033a5b8fcf7039159e35b6878f106ccd5fb35f\auto-service-1.0-rc2.jar

File 2: abc\.gradle\caches\modules-2\files-2.1\com.pushtorefresh.storio\sqlite-annotations-processor\1.2.1\ac96eb5d2267f6e6e457a0e9e3a2f482782a1b08\sqlite-annotations-processor-1.2.1.jar

this helped:
```exclude 'META-INF/services/javax.annotation.processing.Processor'```

**Comment by artem-zinnatullin** [comment]
I'll close this since it's not the problem of StorIO itself, but a problem of dependencies with same info in META-INF.

@Rainer-Lang thanks for publishing, may be it'll help somebody who will google that!
