### ISSUE TITLE
Is InsertOrReplace possible with StorIO?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#506]

**Comment by nikitin-da** [comment]
Yep, `put` it's `insert` and `update` combination.
[DefaultPutResolver](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/DefaultPutResolver.java) firstly queries appropriate rows and then updates or inserts.

**Comment by Rainer-Lang** [comment]
Thanks.

**Comment by artem-zinnatullin** [comment]
You may use any SQL things that you want, even `execSQL()`!

@Rainer-Lang we wanted to use GitHub issues only for bugs and feature requests, could you please ask such questions on StackOverflow with `storio` tag? :)

**Comment by Rainer-Lang** [comment]
Ok. Please excuse me.

**Comment by artem-zinnatullin** [comment]
Never mind :)

**Comment by Rainer-Lang** [comment]
@artem-zinnatullin Is it possible that you add InsertOrReplace to one of the next versions? I really need it.

**Comment by artem-zinnatullin** [comment]
It will be in 1.5.0! See https://github.com/pushtorefresh/storio/issues/521

сб, 26 Сен 2015, 21:09, Rainer-Lang <notifications@github.com>:

> @artem-zinnatullin <https://github.com/artem-zinnatullin> Is it possible
> that you add InsertOrReplace to one of the next versions? I really need it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/506#issuecomment-143476952>
> .
>
-- 

@artem_zin
