### ISSUE TITLE
String as PrimaryKey possible in StorIO?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#507]
Just to be sure... :-)

**Comment by artem-zinnatullin** [comment]
If you are talking about StorIOSQLite annotation processor — then the answer is yes :)

StorIO does not force you use only primary key from the SQLite table, you can do any kinds of "logical keys" for Put operation.

**Comment by Rainer-Lang** [comment]
Thanks - I'm using uuid's.

**Comment by artem-zinnatullin** [comment]
Closing :)
