### ISSUE TITLE
Are here other StorIO users?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#508]
Just to want know if there are other devs using this lib.
Maybe a community could be established to help each other...

**Comment by TheRishka** [comment]
I'm using it in my new app:) Quite poor sample app without more complicated examples, therefore it takes some time to put it in real production. But Rx usage is awesome :+1:

**Comment by Rainer-Lang** [comment]
Do you have this case:
Do first someting (delete,...) in db and then insert some data?

**Comment by artem-zinnatullin** [comment]
I'll close this, JFYI you can ask a question on StackOverflow with `StorIO` tag and will answer it :)
