### ISSUE TITLE
Add option to change or remove default Rx scheduler

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#511]
There are few problems with setting `subscribeOn(Schedulers.io())` by default:

* User can not change this behavior.
* If user adds `subscribeOn()` to already configured observable — he just adds unnecessary work to the Rx chain because it'll switch to user thread and then switch to our initial setting — `Schedulers.io()` anyway.
* Some combinations of StorIO Observables may cause deadlocks because of transactions + forced multithreading (not a bug).

This is incompatible change so I am moving it to v2.0.0

**Comment by artem-zinnatullin** [comment]
Btw, we can allow user pass scheduler in the builder of `DefaultStorIO` and don't apply it if it's `null`, this will allow save old apps from adding `subscribeOn()` everywhere and remove default scheduling for those who don't need it. Also, it'll allow change `Scheduler` to custom one.

@nikitin-da, @karlicoss: thoughts?

**Comment by nikitin-da** [comment]
I agree that it will be a way better - add an ability to configure default scheduler without breaking api. We just need to correct issue name.

**Comment by artem-zinnatullin** [comment]
Can this go into next version please? Maybe 1.10.0

**Comment by nikitin-da** [comment]
Sure

**Comment by artem-zinnatullin** [comment]
Thanks man :)
