### ISSUE TITLE
Rename Internal to LowLevel  

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#516]
`Internal` is a name for something that should not be used by others, but we allow users to use our `StorIOSQLite.Internal` and `StorIOContentResolver.Internal` APIs for Operation resolvers and so on, so I guess, we should rename it to make things clearer.

@nikitin-da and anybody who interested in this, what is your opinion?

**Comment by nikitin-da** [comment]
I agree. Maybe I'd be afraid to use `internal` with such name.

**Comment by Rainer-Lang** [comment]
Internal is really a bit strange. :-)
