### ISSUE TITLE
for db-upgrade

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#527]
In SampleApp there is:
```public DbOpenHelper(@NonNull Context context)```

but shouldn't it be:
```public DatabaseHelper(Context context, String dbName, null, int dbVersion)```?

Or should be the db-version-number be provided directly with a constant?
```java
public DbOpenHelper(@NonNull Context context) {
    super(context, Constant.DB_NAME_STORIO, null, Constant.DB_VERSION);
}
```

What's the preferred way with StorIO?

**Comment by artem-zinnatullin** [comment]
>What's the preferred way with StorIO?

It does not related to StorIO at all :)

Usually we use constructor with just `context` in our projects.
