### ISSUE TITLE
Support for AutoValue in annotation processors

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#528]

**Comment by geralt-encore** [comment]
@artem-zinnatullin can you elaborate more on this one? I know what AutoValue is and I am genuinely interesting in annotation processing because I have never done it before. So it could be pretty interesting for me to implement.

**Comment by artem-zinnatullin** [comment]
@geralt-encore great!

So, basically StorIO has simple annotation processors (for StorIOSQLite and StorIOContentResolver) that user can use to genereate boilerplate code for Put, Get and Delete resolvers.

But at the moment our annotation processors don't support classes with Builders or static factory methods -> they don't support AutoValue.

I'd suggest you just play with sources of our annotation processors and take a look on how we inspect and generate the code.

You can watch couple of talks about annotation processing: 

* https://www.youtube.com/watch?v=dOcs-NKK-RA
* https://www.youtube.com/watch?v=dBUAqPs0TB0

And read some articles (I can't remember them).

To generate the code we use [JavaPoet](https://github.com/square/javapoet).

**Comment by artem-zinnatullin** [comment]
We can start with support for static factory methods, then think about Builders support!

**Comment by geralt-encore** [comment]
Ok, thanks for an introduction. I will start digging into it soon. If I would have any questions - I'll post them here.

**Comment by artem-zinnatullin** [comment]
Sure! Annotation processing is actually interesting part of JDK!

**Comment by geralt-encore** [comment]
@artem-zinnatullin I have a question regarding support of static factory methods. Should we annotate abstract methods representing fields of an object or just factory method and parse its parameters? Or maybe we should annotate both to be sure about how we are creating object because empty package-local constructor doesn't work in this situation? I wanna your approval before starting actual coding.

**Comment by artem-zinnatullin** [comment]
We should annotate both, take a look on Jackson `@JsonProperty` and `@JsonCreator` usage semantic (not implementation)

**Comment by geralt-encore** [comment]
I have one more question regarding this issue. Should we use the same `StorIOSQLiteColumn` annotation for `AutoValue` abstract methods for fields or introduce a new one? I am not sure, because, one the one hand, their share a lot, but on the other - they need completely different validation.

**Comment by artem-zinnatullin** [comment]
I guess, we should use the same annotation, yeah, it'll require completely different validation…

**Comment by talenguyen** [comment]
How about this progress? I am caring about this issues, maybe I can give a hand to help.

**Comment by PaulWoitaschek** [comment]
Any news on this? Would make storio my dream db ;-)

**Comment by artem-zinnatullin** [comment]
I'm currently not using AutoValue… @nikitin-da, @geralt-encore?

**Comment by nikitin-da** [comment]
Right now I don't use processing. 
I would like to work on this after precompiled statement support.

**Comment by geralt-encore** [comment]
I really would like to help with this. I've started it couple of times, but it was too big and I had something more important to do, so  I never wasn't able to finish it.

**Comment by geralt-encore** [comment]
I am going to start working seriously on this issue next week. Hope will have something to show by the end of the week.

**Comment by artem-zinnatullin** [comment]
Yay 🎉

**Comment by geralt-encore** [comment]
My initial plan:

- Allow to annotate methods with `StorIOSQLiteColumn ` and perform all the necessary validations
- Introduce new annotation for factory methods or constructors for marking methods/constructors for creating an object
- The hardest part is to map column fields with factory methods/constructors fields. Do you think that it will be good enough to do it based on the order of fields? I don't see better solution without providing additional metadata to columns, which is redundant in my opinion

How does it sound?

**Comment by artem-zinnatullin** [comment]
2nd item is especially interesting (I didn't though about additional annotation for constructor, but I like its explicitness). Regarding third item — if you can get parameter names of the constructor, that would be good, but if you can't — then sure use order of the parameters.

SGTM!

**Comment by geralt-encore** [comment]
This one can be closed now.
