### ISSUE TITLE
Add support for rx.Single

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#529]

**Comment by geralt-encore** [comment]
@artem-zinnatullin сan you provide a little bit more info about this feature?

**Comment by artem-zinnatullin** [comment]
Basically it's a kind of `Observable` (actually it's a separate class) but it emits result once, useful for getting result once via Rx and not care about updates.

You can get same result via `observable.first()`.

**Comment by geralt-encore** [comment]
@artem-zinnatullin I've started digging into `Single` implementation and just want to hear your opinion about it. This is how I've partially implemented it:

1. Added `createSingle` to `PreparedOperation' interface
2. Created `OnSubscribeExecuteAsBlockingSingle' ([gist] (https://gist.github.com/geralt-encore/57a12f193cb4748af98d))
3. Implemented `createSingle` for `PreparedGetListOfObjects`, for instance, as:

```java
    @NonNull
    @Override
    public Single<List<T>> createSingle() {
        throwExceptionIfRxJavaIsNotAvailable("createSingle()");

        return Single.create(OnSubscribeExecuteAsBlockingSingle.newInstance(this))
                .subscribeOn(Schedulers.io());
    }
```
And here how it looks like in test:
```java
    @Test
    public void getListOfObjectsSingle() {
        Single<List<User>> singleUsers = storIOSQLite()
                .get()
                .listOfObjects(User.class)
                .withQuery(Query.builder()
                        .table("users")
                        .where("email = ?")
                        .whereArgs("artem.zinnatullin@gmail.com")
                        .build())
                .withGetResolver(UserTableMeta.GET_RESOLVER)
                .prepare()
                .createSingle();
    }
```
If it is a right approach then I will start implementing and testing support for `Single` for all possible cases.

**Comment by artem-zinnatullin** [comment]
Yup, looks good!

Can you please name it `asRxSingle()` instead of `createSingle` because `Single` is very generic word and may mislead somebody. I think we'll deprecate `createObservable` and rename it to `asRxObservable()` in same release.

Looking forward to see PR!

**Comment by geralt-encore** [comment]
Sure. And one more question. Should I unsubscribe from `Single`?

**Comment by artem-zinnatullin** [comment]
No :)

**Comment by geralt-encore** [comment]
Damn, I knew it :(

**Comment by artem-zinnatullin** [comment]
@geralt-encore moved to v1.8.0! We'll review your PR soon and I hope v1.8.0 will be released soon after 1.7.0

Everybody: I'm checking if everything is okay with 1.7.0 and will try to prepare release in a few hours.

**Comment by geralt-encore** [comment]
@artem-zinnatullin this one could be closed now I guess

**Comment by artem-zinnatullin** [comment]
Yay!
