### ISSUE TITLE
"orderby XYZ collate nocase" possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#540]

**Comment by artem-zinnatullin** [comment]
Should work! StorIO does nothing special with values passed to `Query`, it just redirects them to `SQLiteDatabase.query()` so if `SQLiteDatabase.query()` can handle this — StorIO will do this too!

So, I'd suggest to try and and comment here about results! (I won't be able to do this next 5-6 hours)

**Comment by artem-zinnatullin** [comment]
@Rainer-Lang I am closing this, since it's not related to StorIO.

Feel free to comment!

**Comment by Rainer-Lang** [comment]
Only for completeness:
```Query.builder().table(TABLE).orderBy(COL_NAME + " COLLATE NOCASE ").build();```
...works for me.

**Comment by artem-zinnatullin** [comment]
:+1: (btw, I think space after `NOCASE` is not needed)

**Comment by Rainer-Lang** [comment]
I just wanted to give a further information about this for ```ContentResolver```:
```sortOrder(...)``` works with ```COLLATE NOCASE``` too
