### ISSUE TITLE
Interceptors API

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#542]
Yes, Interceptors!

Why?
- Logging via interceptors
- Stetho integration via interceptor
- Request behavior changes via interceptor

**Comment by Rainer-Lang** [comment]
May I ask for the status?

**Comment by nikitin-da** [comment]
Hi, @Rainer-Lang !
Sorry, but I haven't started to implement it yet =(
As it may affect current api it will be possible in v2.0.0
Do you want it for logging?

**Comment by Rainer-Lang** [comment]
@nikitin-da Yes for logging. I don't want to log via ```doOnNext()``` or something else. I think logging would be really great. But please, I don't want to rush you. Take your time. :)
"When it's done - it's done." :)

**Comment by artem-zinnatullin** [comment]
Closed by #771.
