### ISSUE TITLE
Multiple parameters in the method orderBy when creating queries

### ISSUE THREAD

**Issue by oneassasin** [pushtorefresh/storio#564]
Please, add, becouse options for sorting can be many.

**Comment by artem-zinnatullin** [comment]
You can specify multiple columns divided by `,` in `orderBy` clause. We've followed same semantic as `SQLiteDatabase.query()`.

Example:

```java
storIOSQLite
  .get()
  ...
  .withQuery(Query.builder()
    .table("some_table")
    .orderBy("column1, column2")
    .build())
```

**Comment by oneassasin** [comment]
```
@NonNull
public CompleteBuilder orderBy(@Nullable String orderBy) {
    this.orderBy = orderBy;
    return this;
}
```
StorIOSQLite 1.6.1

**Comment by artem-zinnatullin** [comment]
Yep, this `orderBy` string can contain multiple columns divided by comma `,` :smile:

**Comment by oneassasin** [comment]
Ooops. I do not write what he wanted. :smile:  
Why do I generate this line, if you can do it within the library :question:

**Comment by artem-zinnatullin** [comment]
Simply because we don't want to do any kind of SQL parsing/processing/generating in the StorIO, it's not an ORM, it's a DAO. The same is applicable to `Query.where()` and `Query.limit()`.
