### ISSUE TITLE
performance enhancement

### ISSUE THREAD

**Issue by pskink** [pushtorefresh/storio#566]
i have been using storio from yesterday and i don't fully understand why `DefaultPutResolver#performPut` uses a `Cursor` to find out whether to call insert or update which degrades the performance a bit, why not internally use `storIOSQLite.internal().insertWithOnConflict()` with `android.database.sqlite.SQLiteDatabase#CONFLICT_REPLACE` conflictAlgorithm? that way `mapToInsertQuery` and `mapToUpdateQuery` could be unified maybe?

**Comment by artem-zinnatullin** [comment]
Simply because logical check on our side gives more predictable result,
especially if you have multiple logical keys which is possible.

Feel free to change implementation to insertWithOnConflict!

On Mon, Nov 23, 2015, 17:51 pskink <notifications@github.com> wrote:

> Closed #566 <https://github.com/pushtorefresh/storio/issues/566>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/566#event-472126095>.
>
-- 

@artem_zin
