### ISSUE TITLE
Also for SQLite: Option to get one object  for executeAsBlocking for ContentResolver?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#567]
Is this planned for SQLite (not ContentResolver)?

**Comment by artem-zinnatullin** [comment]
Already merged another PR for SQLite!

On Fri, Dec 4, 2015, 20:37 Rainer-Lang <notifications@github.com> wrote:

> Is this planned for SQLite (not ContentResolver)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/567>.
>
-- 

@artem_zin

**Comment by Rainer-Lang** [comment]
Thanks + closing

**Comment by artem-zinnatullin** [comment]
JFYI we didn't ship new version yet, so I'll close it when we'll ship new StorIO!

**Comment by geralt-encore** [comment]
@Rainer-Lang as I remember this one has already merged

**Comment by artem-zinnatullin** [comment]
Oh, yep was released in v1.7.0!

And we use it pretty heavily :)
