### ISSUE TITLE
Unit Tests for improved test coverage

### ISSUE THREAD

**Issue by mfarid** [pushtorefresh/storio#571]
Will it be helpful if I write some unit tests for certain modules to improve overall tested code coverage.

**Comment by artem-zinnatullin** [comment]
@mfarid sure! You can start with small PR and few tests!

**Comment by mfarid** [comment]
@artem-zinnatullin Thanks a lot for quick response, I will start with a small PR with few tests, just as you suggested.

**Comment by artem-zinnatullin** [comment]
@mfarid great! Just curious with what class do you want to start? :smile:

**Comment by mfarid** [comment]
@artem-zinnatullin I have not identified any specific class as of now, if you would like me to target something specific, please let me know. Otherwise, once I start with some tests I will update this ticket with the same.

**Comment by artem-zinnatullin** [comment]
I have a solution! We have tests coverage which seems to be broken for last
month because flucking Gradle things, let me fix test coverage measurement
and then we'll see what classes need more tests, okay?

On Mon, Dec 14, 2015, 07:49 Mohd Farid <notifications@github.com> wrote:

> @artem-zinnatullin <https://github.com/artem-zinnatullin> I have not
> identified any specific class as of now, if you would like me to target
> something specific, please let me know. Otherwise, once I start with some
> tests I will update this ticket with the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/571#issuecomment-164342263>
> .
>
-- 

@artem_zin

**Comment by mfarid** [comment]
Sounds great, thanks.

**Comment by artem-zinnatullin** [comment]
@mfarid yay! You can now pull the repository and run `ci.sh` and then find Jacoco reports about test coverage in `module/build/reports/` for each module!

**Comment by mfarid** [comment]
Thanks @artem-zinnatullin I appreciate it.
Ii will start with a small module and send out a PR to you soon.

**Comment by artem-zinnatullin** [comment]
Great, thanks @mfarid! You can start even with one or two tests so code review will be fast :)

**Comment by artem-zinnatullin** [comment]
Looks like this one can be closed :)
