### ISSUE TITLE
Add ability to dynamically change uri or update condition for put() method

### ISSUE THREAD

**Issue by xdmaolei** [pushtorefresh/storio#581]
when I call StorIOContentResolver.put(), it's hard to change uri or update condition(where, whereArgs), usually I need to implement different putresolvers and hardcode them

**Comment by coofee** [comment]
Why put method cannot use query like get? just like below code. It's a design or has other reason.


```java
storIOSQLite
                .put()
                .objects(tweets)
                .withQuery("pass query")
                .prepare()
                .createObservable()
```

**Comment by artem-zinnatullin** [comment]
Please see #606 where I commented why we can't do this for Put Operation (TL; TR; it's responsibility of Put Resolver because Put is non trivial operation: update or insert).
