### ISSUE TITLE
Remove `createObservable()` and replace it with `asRxObservable()`

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#582]

**Comment by inorichi** [comment]
Suggestion: rename also `executeAsBlocking` to `asBlocking`.

Everything would have the same format: `asSomething`

**Comment by artem-zinnatullin** [comment]
Well, we want strongly show that this method will execute operation in
current thread as soon as you call it while other methods are lazy

On Sun, 24 Jan 2016, 18:25 inorichi <notifications@github.com> wrote:

> Suggestion: rename also executeAsBlocking to asBlocking.
>
> Everything would have the same format: asSomething
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/582#issuecomment-174309340>
> .
>
-- 

@artem_zin

**Comment by artem-zinnatullin** [comment]
It's part of #607, I'm closing all other issues about deprecated apis.
