### ISSUE TITLE
Date Annotation

### ISSUE THREAD

**Issue by BraunreutherA** [pushtorefresh/storio#583]
In the Annotation Processor Dates are not supported. What's the intended way to get date and time into the db?

Best,
Alex

**Comment by artem-zinnatullin** [comment]
This will be a part of #475!

JFYI: annotation processor is totally optional and you can always write custom Put, Get and Delete Resolvers with needed behavior, you can mix generated and manual code if you wish!

So, at the moment I'll recommend write custom Get and Put resolver or store the field as `long` milliseconds.

**Comment by artem-zinnatullin** [comment]
If you don't mind, I'll close this issue in favor of #475. Feel free to comment here or (better) there #475!
