### ISSUE TITLE
Better support for fields nullability by Annotation Processors

### ISSUE THREAD

**Issue by xdmaolei** [pushtorefresh/storio#595]
public ContentValues mapToContentValues(@NonNull ReplyBean object) {
        ContentValues contentValues = new ContentValues(2);

        if(object.content != null){
            contentValues.put("content", object.content);
        }
        if(object.key!= null){
            contentValues.put("key", object.key);
        }
       
        return contentValues;
    }

First I appreciate your work, I think It will be helpful to check the properties whether they are null, and the properties should be non-primitive

**Comment by artem-zinnatullin** [comment]
Well, columns may be null in SQLite. But we may add support for Nullability annotations in our annotation processor, will it be ok for you?

**Comment by xdmaolei** [comment]
Thanks, it'll be OK

**Comment by nikitin-da** [comment]
Hi, @xdmaolei!
We may add property `ignoreNull` for annotation processor, but it will be quite difficult to clear this field. 
Is it acceptable for your case or do you see a way to clear, except using another put resolver?
