### ISSUE TITLE
Put error message is wrong

### ISSUE THREAD

**Issue by fusion44** [pushtorefresh/storio#604]
Hi,

first, thank you for this awesome library! Its so simple and fun to use. :)

I've found a small but confusing typo. I'm getting the message "Error has occurred during Delete operation." after a failed PUT operation. You can find the code [here.](https://github.com/pushtorefresh/storio/blob/515f740a210c702b5bda170afcb07b4391b2f6e1/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/PreparedPutContentValues.java#L58)

Thanks!

**Comment by artem-zinnatullin** [comment]
Damn, my bad! We'll fix it! Thanks for report and feedback :)

**Comment by fusion44** [comment]
No problem. Thanks for the quick feedback!

**Comment by artem-zinnatullin** [comment]
We'll close it once we fix it!
