### ISSUE TITLE
Put operation between different tables

### ISSUE THREAD

**Issue by pavlospt** [pushtorefresh/storio#606]
Hello.

Is there a way to store objects between different tables using the same StorIOSQLite object? 

I tried by adding a custom PutResolver for the put operation on the second Table, but i do not seem to get it right based on the Docs. 

Any hints or something that i can try?

Thanks in advance.

**Comment by artem-zinnatullin** [comment]
To be sure: you want to store one object in multiple tables?

On Tue, 26 Jan 2016, 23:02 Pavlos-Petros Tournaris <notifications@github.com>
wrote:

> Hello.
>
> Is there a way to store objects between different tables using the same
> StorIOSQLite object?
>
> I tried by adding a custom PutResolver for the put operation on the second
> Table, but i do not seem to get it right based on the Docs.
>
> Any hints or something that i can try?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pushtorefresh/storio/issues/606>.
>
-- 

@artem_zin

**Comment by pavlospt** [comment]
@artem-zinnatullin let's say multiple same objects in two different tables. Example use case is: some cached data and some saved data by choice.

**Comment by artem-zinnatullin** [comment]
aha, got it.

I'd suggest to write custom `PutResolver` via extending basic `PutResolver` instead of `DefaultPutResolver` and there you can do whatever you want to do :)

Just don't forget to wrap your code into transaction via `storIOSQLite.internal().beginTransaction()`, `setTransactionSuccessful()` and `endTransaction()` to keep db consistent!

**Comment by artem-zinnatullin** [comment]
// For future: please ask such questions on StackOverflow with `storio` tag, we try to keep GitHub issues for bugs and feature requests :)

**Comment by pavlospt** [comment]
@artem-zinnatullin Is there any practical example of such a use case somewhere that I can see the implementation of it? 

Didn't know about the SO tag, excuse me for that!

**Comment by artem-zinnatullin** [comment]
No, but presoudo-code will look like this:

```java
class CustomPutResolver extends PutResolver<MyObject> {

  @Override 
  @NonNull
  public PutResult performPut(@NonNull StorIOSQLite storioSQLite, @NonNull MyObject object) {
    storIOSQLite.internal().beginTransaction();

    try {
      // Decide what to do: insert or update or insertWithOnConflict, etc.
      storIOSQLite.internal().insert("table1", objectAsContentValues);
      storIOSQLite.internal().insert("table2", objectAsContentValues);
      storIOSQLite.internal().setTransactionSuccessful();
    } finally {
      storIOSQLite.internal().endTransaction();
    }
  }
}
```

P.S. sorry for `storIOSQLite.internal()`, actually it's part of public API and in the next release we'll rename it to `lowLevel`!

>Didn't know about the SO tag, excuse me for that!

No problems :)

Hope it answers your question! If so — please close the issue :)

**Comment by pavlospt** [comment]
Hello. 

Thanks for your answer. That answers my question. 

Thanks a lot again.

**Comment by pavlospt** [comment]
Edit (cause of reopening): Will there be any way to add this ability on the API level of the .put() method or after it? Like .fromTable(Table_Name) ?

**Comment by artem-zinnatullin** [comment]
No, since Put is operation that fully depends on Put Resolver to figure out how to perform it (insert or update).

I mean, from the point of API design it will be really hard to support kind of queries for Put operation, because it's more complex than Get and Delete.

Sorry…
