### ISSUE TITLE
Error on Get operation when using Like operator

### ISSUE THREAD

**Issue by pavlospt** [pushtorefresh/storio#609]
Hello. 

I think there is a bug during the use of the Get operation with a "like" operator in the query builder.

For example: When using the following "where" text:

`
.where(FoodTable.COLUMN_TITLE + " like ' " + term + "%' ")
`
everything works as expected. 

Although if i try to rewrite it in the following way, an error occurs: 

`
.where(FoodTable.COLUMN_TITLE + " like '?%' ")
.whereArgs(term)
`

The occurring error: 
`
Error has occurred during Get operation. query = Query{distinct=false, table='SavedFoods', columns=[], where='title like '?%'', whereArgs=[bana], groupBy='', having='', orderBy='', limit=''}
`

**Comment by artem-zinnatullin** [comment]
Not a bug of StorIO. 

`Query` is container for all params for `SQLiteDatabase.query()`, so you can google how to make query with `LIKE` to `SQLiteDatabase`, take a look at [this](http://stackoverflow.com/questions/9076561/android-sqlitedatabase-query-with-like) and [this](http://stackoverflow.com/questions/9076561/android-sqlitedatabase-query-with-like) questions on StackOverflow.

Just tried:

```java
where(FoodTable.COLUMN_TITLE + " LIKE ?").whereArgs(term + "%")
```

And:

```java
where(FoodTable.COLUMN_TITLE + " LIKE ? || '%'").whereArgs(term)
```

Both worked great.

Hope that helps!

**Comment by pavlospt** [comment]
Ok thanks for the response. I tried it before on a pure SQLiteContentProvider and i was using it with the single quotes style. That's what caused me to think that this is a bug and not a misuse. Can this be placed somewhere on the docs maybe, for future reference?

**Comment by artem-zinnatullin** [comment]
We will mention that `Query` is simple wrapper for `SQLiteDatabase.query()` params in the docs! Here is the issue for that #602.

**Comment by pavlospt** [comment]
Great! Thanks once again for the immediate reply.

**Comment by artem-zinnatullin** [comment]
You're welcome :)
