### ISSUE TITLE
Partial Put

### ISSUE THREAD

**Issue by Denvar** [pushtorefresh/storio#612]
Hey guys

There are times when dealing with APIs where a model will sometimes have extra attributes when returned from some endpoints compared to others.

For example: /events return a list of Event objects with a members_count attribute.
Later calling /events/<event_id> returns the same vent but without a members_count.

With the standard StorIO setup (without defining separate POJO) PUTing the event from the second call will set the event's members_count to null.

A workaround I have is to check if the event already exists in the DB, query it, set the members_count on the new instance of the event then PUT the new instance in to the DB.

Is there a better way to do this? This can get complicated as entity attribute presence differs.

Alternatively is there a "StorIO" way of performing INSERT without UPDATE? That way I can stop PUTs with the missing attributes from overriding an existing DB entry. (not ideal still)

**Comment by artem-zinnatullin** [comment]
Hi, @Denvar!

Sad case, but definitely solvable via StorIO! Looks like you need simple thing — custom `PutResolver`.

>Alternatively is there a "StorIO" way of performing INSERT without UPDATE? That way I can stop PUTs with the missing attributes from overriding an existing DB entry. (not ideal still)

As said, I'd suggest to simply add `PutResolver` for your type and implement all the logic you need to do there, here is pseudo code:

```java
class MyTypePutResolver extends PutResolver<MyType> {

  @Override
  public PutResult performPut(@NonNull StorIOSQLite storIOSQLite, @NonNull MyType object) {
    final StorIOSQLite.Internal internal = storIOSQLite.internal(); // It's public part of the API, we're renaming it to LowLevel in v1.9.0

    internal.beginTransaction(); // For data consistency.

    try {
      final MyType objectFromDb = storIOSQLite
        .get()
        .object(MyType.class) // Yup, why not use all the power of StorIO here?
        .withQuery(Query.builder()
          .table(MyTypeTable.TABLE_NAME)
          .where(MyTypeTable.COLUMN_SOME_ID + "=?")
          .whereArgs(object.someId())
          .build())
        .prepare()
        .executeAsBlocking();

      if (objectFromDb == null) {
        // Then do INSERT.
        internal.insert(…, object.toContentValues()); 
      } else {
        // Do UPDATE.
        // Here you can decide what columns to update.
        // You logic here…
        internal.update(…, contentValuesWithRequiredColumns);
      }

      internal.setTransactionSuccessful();
    } finally {
       internal.endTransaction();
    }
  }
}
```

**Notice** that you can mix resolvers generated via annotation processing with handmade ones, for example you can still use generated `Get` and `Delete` resolvers and use handmade `Put` resolver.

Hope that helps! Feel free to comment and reopen the issue if needed :)
