### ISSUE TITLE
 Compatibility with the properties of Kotlin

### ISSUE THREAD

**Issue by georgeci** [pushtorefresh/storio#614]
I want to generate `SQLiteTypeMapping` in Kotlin with [kapt](http://blog.jetbrains.com/kotlin/2015/05/kapt-annotation-processing-for-kotlin/). But all fields are private in Kotlin. There are open only getter and setter.

```
@StorIOSQLiteColumn(name = NAME, key = true)
var name: String = ""
```

I had this exception
`Error:StorIOSQLiteColumn can not be applied to private field: name`

In OrmLite I can do it like [this](http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_2.html#index-field-access-using-getters-and-setters):

```
@DatabaseField(useGetSet = true)
private Integer orderCount;
public Integer getOrderCount() {  return orderCount;}
public void setOrderCount(Integer orderCount) {  this.orderCount = orderCount;}
```

**Comment by artem-zinnatullin** [comment]
Right, because OrmLite uses reflection while we don't.

In #528 @geralt-encore works on support for AutoValue which will add support for getters -> partially help with support for Kotlin.

For now I'd just suggest override `DefaultPutResolver`, `DefaultGetResolver` and `DefaultDeleteResolver` for your data classes, it's really easy :)

**Comment by geralt-encore** [comment]
Didn't have much time, but still working on it. Kotlin support would be great feature to deal with next!

**Comment by hotchemi** [comment]
HI, any concrete plan to support it?

**Comment by bluebery** [comment]
+1 hoping for this support!!

**Comment by tseglevskiy** [comment]
Folks, are you going to support it?

**Comment by pbochenski** [comment]
+1

**Comment by artem-zinnatullin** [comment]
PR is welcome :)

Ideas for possible implementation:

1. Allow apply `@StorIOSQLiteColumn` to methods (that will allow us work with getters and setters which Kotlin generates for `var/val`.)
2. Handle methods starting with `get/set` in annotation processor, notice that `val` won't have `set`
3. Handle creation of class instance through constructor call with parameters (most significant part).
4. …
5. PROFIT!

**Comment by geralt-encore** [comment]
This one can be closed now.
