### ISSUE TITLE
how to perform an update?

### ISSUE THREAD

**Issue by thomasdola** [pushtorefresh/storio#615]
am really confused..
have been trying it for hours but error..
any help?
by the not only update?  ==> get a single object too..
thanks

**Comment by thomasdola** [comment]
any one there?
please...

**Comment by artem-zinnatullin** [comment]
StorIO has three basic operations: Put, Get and Delete. 

Update is part of Put. Everything is in documentation and readme, also, we have a sample app in the repo and a lot of tests (even design tests where you can find out how to use StorIO).

**Comment by thomasdola** [comment]
am a beginner in android development so if you could just give a simple example of an update using the Put...

**Comment by artem-zinnatullin** [comment]
Idk what exactly will help you, but basic code is

```java
storIO
 .put()
 .object(someObject)
 .prepare() 
 .executeAsBlocking()
```

I'd say, that to use StorIO you need some understanding of storage APIs (`SQLiteDatabase` or `ContentResolver`)  in Android.

**Comment by thomasdola** [comment]
I solved my issue
i forgot to apply `take(1)` to my Observable while updating , so it was just running the code over and over...
thank you so much for this awesome library...

**Comment by artem-zinnatullin** [comment]
Oh, got it. Well, please ask more precise questions with code samples next time :) 

BTW, you can use `asRxSingle()` instead of `asRxObservable().take(1)`
