### ISSUE TITLE
Migrate from Greendao to StorIO

### ISSUE THREAD

**Issue by jpmassena** [pushtorefresh/storio#616]
Hi, 

I'd like to know if it's possible to migrate from Greendao to StorIO without losing existing data.

**Comment by artem-zinnatullin** [comment]
Yes, it's possible!

StorIO does nothing about creation and updating of the database, it just attaches to the existing one via `SQLiteOpenHelper` or `ContentResolver` (which may be not even a db). 

Just use `SQLiteOpenHelper` that will open existing db and you should be good to go!
