### ISSUE TITLE
A SQLiteConnection object for database '/data/data/primr.apps.eurakacachet.com.primr/databases/ryme.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

### ISSUE THREAD

**Issue by thomasdola** [pushtorefresh/storio#621]
Any idea what might be the cause of that?
thanks.

**Comment by artem-zinnatullin** [comment]
Do you use your DB only through StorIO?  Do you manually use `StorIO.Internal`?

**Comment by thomasdola** [comment]
Yes only through StorIO..
not seeing that again for now. but what could be the cause?

**Comment by artem-zinnatullin** [comment]
Do you manually call close on the db or `StorIOSQLiteDatabse`?

**Comment by artem-zinnatullin** [comment]
@nikitin-da, @karlicoss do you see this in the Yandex project that uses `StorIOSQLite`?

**Comment by karlicoss** [comment]
Yup

**Comment by nikitin-da** [comment]
No, I don't

**Comment by karlicoss** [comment]
Update: disregard my previous comment, I got confused. I haven't seen them
as well.

**Comment by artem-zinnatullin** [comment]
ok, I'm going to close this because I don't see leaks inside of the StorIO and I guess it's problem of particular app…
