### ISSUE TITLE
Updating a row with null value

### ISSUE THREAD

**Issue by sreejithraman** [pushtorefresh/storio#624]
I don't know if I am missing something but if I try to update a row with some columns as null, it doesn't seem to be reflected

**Comment by artem-zinnatullin** [comment]
StorIO simply passes `ContentValues` to `SQLiteDatabase` or `ContentResolver` methods…

We'll write test for that and see if it's real problem or not, I believe we put `null` in our apps without problems.

**Comment by artem-zinnatullin** [comment]
@nikitin-da can you please take this? It may affect apps you're working on :)

(I'm pretty busy unfortunately…)

**Comment by nikitin-da** [comment]
@artem-zinnatullin, sure, I'll take it tomorrow
