### ISSUE TITLE
rx.Completable support

### ISSUE THREAD

**Issue by geralt-encore** [pushtorefresh/storio#628]
What do you think about using `Completable ` for put/delete operation?

**Comment by artem-zinnatullin** [comment]
Yup, it's possible

**Comment by geralt-encore** [comment]
Will add this feature to ContentResolver in a couple of days

**Comment by artem-zinnatullin** [comment]
Great, thanks!

**Comment by artem-zinnatullin** [comment]
Awesome work, @geralt-encore, thanks a lot!
