### ISSUE TITLE
How to ensure that a column won't get overriden by a null value?

### ISSUE THREAD

**Issue by sreejithraman** [pushtorefresh/storio#639]
Let's say I have a simple `user` table with the following columns: `name`, `id`, `token`. 

Sometimes `token` is given to me and in those cases update `token`. Other times token will be null and in those cases I just want to keep the existing value inside `token`. 

One way I thought of was to make a put resolver. Inside the resolver, I check if the given `user` already has a value for token. If it doesn't, I do a get based on the user's `id`. If i get a user back, I grab the token and save that along with the new `user` info.

But won't that basically double the amount of time to insert? I was wondering if there was a quicker way.

**Comment by nikitin-da** [comment]
To get rid inserting the same values, maybe just store `token` in separate table `token` : `user_id`, `token_value`? 
Create put resolver like in [one-to-many example](https://github.com/pushtorefresh/storio/blob/52c18835c611270bc38aa55461731f2205d44b77/storio-sample-app/src/main/java/com/pushtorefresh/storio/sample/db/resolvers/UserWithTweetsPutResolver.java) with custom `performPut`. And here you can insert token only when it is needed and use two hidden resolvers for simple user and token.

**Comment by nikitin-da** [comment]
There is related issue #595

**Comment by nikitin-da** [comment]
For generated resolvers there is `ignoreNull` property (#642).
In custom resolver we should not put `null` to contentValues.
