### ISSUE TITLE
Add new column in existing table

### ISSUE THREAD

**Issue by harcoPro** [pushtorefresh/storio#640]
How i can add new column in existing table and update application for user?

**Comment by sreejithraman** [comment]
Someone correct me if I am wrong but, I think you have to just update it normally. 

````java
 @Override
public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    // If you need to add a column
    if (newVersion > oldVersion) {
        db.execSQL("ALTER TABLE foo ADD COLUMN new_column INTEGER DEFAULT 0");
    }
}
````

**Comment by artem-zinnatullin** [comment]
@harcoPro 

StorIO does not handle scheme of your db, it just connects to the existing one via `SQLiteOpenHelper`.

Just change scheme of db/tables as part of `SQLiteOpenHelper.onUpgrade()` normally and make appropriate changes to the classes that you use with StorIO.

@sreejithraman you're right :)

**Comment by harcoPro** [comment]
thanks!
