### ISSUE TITLE
Use AUTOINCREMENT with storio

### ISSUE THREAD

**Issue by rakam** [pushtorefresh/storio#644]
Hi

Is there any way to use a `INTEGER PRIMARY KEY AUTOINCREMENT` column with storio, in order not to specify an ID when inserting a value for the first time, but still neing able to get the generated id and use it to update the row? (I use Annotation Processor)

Thanks

**Comment by nikitin-da** [comment]
Hi, @rakam!
It seems we should add yet another flag for annotation processor, something like `generatedId`
@artem-zinnatullin, @karlicoss guys what do you think?

**Comment by karlicoss** [comment]
I guess that makes sense

**Comment by artem-zinnatullin** [comment]
Should your ignoreNull help?

**Comment by nikitin-da** [comment]
Hm, actually no. For this case we need to set generated value back into entity

**Comment by artem-zinnatullin** [comment]
As far as I remember this is the only problem with it, that it does not set
generated value to the entity.

But, at the same time you should really consider using immutable entities
for db, so it looks ok to me.

**Comment by artem-zinnatullin** [comment]
Btw, we have a feature request to store object in the PutResult, what if we
store result after Put there so it will be up-to-date after Put operation
and user will be able to retrieve it? cc @karlicoss

**Comment by nikitin-da** [comment]
In terms of immutability entities with result & `ignoreNull` annotation looks fine.
But how can we update or create new instance of unmodifiable entity inside the operation?

**Comment by artem-zinnatullin** [comment]
Just read it from db?

**Comment by nikitin-da** [comment]
Oh, right! 
Ok, I agree.

**Comment by nikitin-da** [comment]
Links to #595 and #623

**Comment by artem-zinnatullin** [comment]
But just for note: it'll affect performance..

**Comment by nikitin-da** [comment]
Yeah=( And will break API compatibility

**Comment by artem-zinnatullin** [comment]
yeah, I'd prefer not to change object passed to Put operation, user can do
this in custom PutResolver

**Comment by nikitin-da** [comment]
To recap it will be resolved by using `ignoreNull` property #642 with custom put resolver or entity from put result (#623)
