### ISSUE TITLE
wiki: executeSQL() shouldn't used for update - why?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#645]

**Comment by nikitin-da** [comment]
There isn't a strict prohibition to do it, but it imposes several drawbacks.
- Can't use resolvers -> query should contain serialization
- It is impossible to obtain the result
- Can't use embedded request arguments escaping -> stay alone with sql injection hazard :scream:
 
So it is preferable use `executeSQL()` for DDL, and `get`, `put`, `delete` for CRUD operations =)

**Comment by Rainer-Lang** [comment]
@nikitin-da Thanks for clarification.
Sometimes it's just necessary to execute just a statement. :)

**Comment by artem-zinnatullin** [comment]
Just as addition, if you need to perform some custom SQL query that does
not fit into our Query object -> please use RawQuery where you can write
any kind of SQL (JOINS, etc) and safely bind arguments to it.

**Comment by Rainer-Lang** [comment]
@artem-zinnatullin Yes, I'm using RawQuery already. Thanks.
