### ISSUE TITLE
How to encrypt data ?

### ISSUE THREAD

**Issue by buaacloud** [pushtorefresh/storio#646]
Hi,

Is there any idea to encrypt data stored in sqlite database,someone said SQLCipher,but it told me 
"Update the import path from android.database.sqlite.* to net.sqlcipher.database.* in any source files that reference it." that is to say,I can't use storio any more?

**Comment by artem-zinnatullin** [comment]
Error seems not related to StorIO.

StorIO is abstraction with default implementation, you can implement it in
a way that it'll use sqlcipher under the hood. Or you can crate wrapper for
SQLiteOpenHelper from sqlcipher and pass it to StorIO.

**Comment by buaacloud** [comment]
Thanks for reply,I know it's not StorIO's Error,I have used StorIO in my project,but I do need data security,so I have  much work to do just as you said.

**Comment by artem-zinnatullin** [comment]
It's not a lot of work, as I said you can try to wrap SQLiteOpenHelper.

**Comment by buaacloud** [comment]
Got it, Thanks for your suggestion!

**Comment by Rainer-Lang** [comment]
@buaacloud What did you do now?

**Comment by Rainer-Lang** [comment]
@keepfit What did you do now?
