### ISSUE TITLE
Conditional insert or replace -> with StorIO better?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#647]
I have following procedure:

1. execute sql-statement: ```select to_update from test where uuid='123-XYZ'``` (```to_update``` is 0 or 1; or ```no-select-data```)
2. if result of ```1.``` is ```1``` or ```no-select-result``` then I have to execute another sql (example): ```insert or update (...) values (...)```

I'm wondering if this could be done with StorIO in an elegant way.....

**Comment by nikitin-da** [comment]
If you really want it, you can extend [PutResolver](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/PutResolver.java) for entity from `2.`. And in `performPut` query `to_update` to decide should you insert/update or do nothing.

But as for me it is not quite elegant way =) Maybe some active model should do it.

**Comment by Rainer-Lang** [comment]
@nikitin-da What would be an elegant way for you? :)
I'm hoping with StorIO there is a cool way to do it.

**Comment by nikitin-da** [comment]
@Rainer-Lang I guess, custom put resolver - it is only way to do it inside StorIO (@artem-zinnatullin, @karlicoss correct me if I'm wrong). 

From my point of view it's preferably to make such decision on a higher level (some domain model that represents business logic). 
Imagine if you will have to check not just `test` table to find out if value up to date. But also obtain some information from shared preferences or smth else. 
It will be improperly to wrap all these logic in StorIO. And in these cases you'll have to completely rewrite your put resolver.

**Comment by Rainer-Lang** [comment]
@nikitin-da I have for all my tables resolvers, so I can do it like you suggested. I'm only afraid of getting 10-50 values instead of only 1 from each table.

**Comment by Rainer-Lang** [comment]
I found a workaround, so I don't need this.
Anyway, @nikitin-da thanks for your effort.
