### ISSUE TITLE
Delete all data from all tables

### ISSUE THREAD

**Issue by riinav** [pushtorefresh/storio#648]
Is there any method which can help in clearing all contents from all the tables. 
something like StorIO.clear()
or Do we need to handle this by our selves?

**Comment by artem-zinnatullin** [comment]
Yeah, for now I'd suggest to handle it yourself, something like:

```java
storIO
  .executeSQL()
  .withQuery(RawQuery.builder()
    .query("custom sql to delete all rows in all tables")
    .args(someArgs)
    .affectsTables(listOfAllTables)
    .build())
```

This will clear all tables and notify all observers. You might also want to drop db file with `context.deleteDatabase()` but make sure you recreate `StorIO` instance then!

See https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/test/java/com/pushtorefresh/storio/sqlite/design/ExecuteSQLOperationDesignTest.java for examples.
