### ISSUE TITLE
Updating parts of Objects

### ISSUE THREAD

**Issue by BraunreutherA** [pushtorefresh/storio#649]
Hi, I've got a similar question to the #612 issue. 

I'm trying to update a timestamp of a message which is sent or received and I just want to update this one field without providing all other fields again. I haven't found a way to do this so I wrote a custom PutResolver:

``` java
    public com.pushtorefresh.storio.sqlite.operations.put.PutResult performPut(@NonNull StorIOSQLite storIOSQLite, @NonNull MessageEntity object) {
        final StorIOSQLite.Internal internal = storIOSQLite.internal();
        PutResult putResult;
        Log.e("test", "Testing if the error occures somewhere here...");
        internal.beginTransaction();

        try {
            final MessageEntity messageEntity =
                    storIOSQLite
                            .get()
                            .object(MessageEntity.class)
                            .withQuery(Query.builder()
                                    .table(MessageTable.TABLE)
                                    .where(MessageTable.COL_UUID + " = ?")
                                    .whereArgs(object.getUuid())
                                    .build())
                            .prepare()
                            .executeAsBlocking();

            Log.e("test", object.toString());

            if (messageEntity != null) {
                Log.e("messagePut", messageEntity.toString());
                messageEntity.setSentAt(new Date().getTime());
                putResult = storIOSQLite
                        .put()
                        .object(messageEntity)
                        .prepare()
                        .executeAsBlocking();
            } else {
                putResult = PutResult.newUpdateResult(0, "");
            }

            internal.setTransactionSuccessful();
        } finally {
            internal.endTransaction();
        }

        return putResult;
    }
```

I'm using the Resolver this way: 

``` java
 public Observable<Void> markMessageSent(Message message) {
        MessageEntity messageEntity = new MessageEntity();
        messageEntity.setUuid(message.getUuid());

        return storIOSQLite
                .put()
                .object(messageEntity)
                .withPutResolver(new MessageMarkSentPutResolver())
                .prepare()
                .asRxObservable()
                .flatMap(receiveMessage -> Observable.empty());
    }
```

But on execution I always get an error Log:
`com.pushtorefresh.storio.StorIOException: Error has occurred during Put operation. object = MessageEntity{uuid='fddc2059-cc5e-4b1f-a218-27a334438552', conversationUuid='null', senderUuid='null', sentAt=1462277457055, receivedAt=0, content='null', type='null'}`

The extremely strange thing is that the sentAt field is 0 before execution so it seams the resolver changes it. But whenever I set some stop points in debug mode the debugger never comes into the Resolver and it seams the Resolver code won't get executed. The Logs in the PutResolver are not executed aswell.

**Comment by Rainer-Lang** [comment]
@BraunreutherA You can use executeSQL()

**Comment by BraunreutherA** [comment]
@Rainer-Lang for sure I could go to the bottom layer but that's not i the sense of the storIO library. So i hope theres a better way.

**Comment by Rainer-Lang** [comment]
@BraunreutherA I see. Maybe it's better to focus on the error message. Your resolver doesn't look so bad :)

**Comment by nikitin-da** [comment]
Hi, @BraunreutherA!
Can you please set breakpoint in [`executeAsBlocking`](https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/put/PreparedPutObject.java#L57) and check the cause of StorIOException.
Branch with provided `explicitPutResolver` is extremely simple, so `performPut` likely should be called.
Or just place Log before `messageEntity` query, to make sure that there is no error.

**Comment by BraunreutherA** [comment]
Hi @nikitin-da 
If edited the resolver here aswell and the log in front doesn't execute.
The breakpoint at executeAsBlocking isn't hit aswell.

**Comment by Rainer-Lang** [comment]
so after ```Log.e("test", "Testing if the error occures somewhere here...");``` there is nothing executed?

**Comment by BraunreutherA** [comment]
No, but I don't understand why the sentAt field is manipulated.. cause if I delete the Line `messageEntity.setSentAt(new Date().getTime());` sentAt stays 0.

**Comment by nikitin-da** [comment]
@BraunreutherA, do you have another put resolvers for `MessageEntity`?) 
What was the cause of StorIOException?

**Comment by BraunreutherA** [comment]
Cause is the following:

`com.pushtorefresh.storio.StorIOException: Error has occurred during Put operation. object = MessageEntity{uuid='7e626104-bb45-4182-a074-6d9b1a549aa4', conversationUuid='null', senderUuid='null', sentAt=1462297655317, receivedAt=0, content='null', type='null'}`

`Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: messages.conversationUuid (code 1299)`

but the messageEntity fields shouldn't be null cause they are set in the put resolver where the messegentity gets fetched from the db.
Yes a default put resolver is set in the beginning with dagger

**Comment by nikitin-da** [comment]
It's weird=) 
Before this fact `if I delete the Line messageEntity.setSentAt(new Date().getTime()); sentAt stays 0.`
I thought that cause was in another put resolver or ignoring `markMessageSent` result.
I try to reproduce it in [test](https://github.com/pushtorefresh/storio/commit/98a537df1624bb6fc181465e3176573f519055fd), but all works fine.
Can you please modify it or provide me with another simple example where I can debug this problem?

**Comment by BraunreutherA** [comment]
Sure I will put together something tomorrow.

**Comment by BraunreutherA** [comment]
Strange.. I've set up the same stuff with your sample application and it works. I've senn that I didn't provide `@StorIOContentResolverColumn` in my entities. Is this the error? :D

**Comment by nikitin-da** [comment]
It is not error if you don't use [`StorIOContentResolver`](https://github.com/pushtorefresh/storio/blob/master/storio-content-resolver/src/main/java/com/pushtorefresh/storio/contentresolver/StorIOContentResolver.java) or annotation processor for it.

**Comment by BraunreutherA** [comment]
Oh my god. Found the error.. Sry guys this was realy dumb from my side. 

```java
       MessageEntity messageEntity = new MessageEntity();
       messageEntity.setUuid(message.getUuid());

        return storIOSQLite
                .put()
                .object(messageEntity)
                .withPutResolver(new PutResolver<MessageEntity>() {
                    @NonNull
```

The naming was wrong so the took the wrong object to insert -.- Sry for stealing your time.

**Comment by nikitin-da** [comment]
Happens to everybody=)
