### ISSUE TITLE
StorIOSQLite: add support for notification tags

### ISSUE THREAD

**Issue by nikitin-da** [pushtorefresh/storio#663]
Add the same thing like [`affectsTables`](https://github.com/pushtorefresh/storio/blob/c8c4f8a58888c97594acef011722f86fed9a0d11/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/queries/RawQuery.java) in all query classes, to make it possible to emit notifications of some 'uris', real tables for which aren't exist.

`storIOSQLite.observeChangesInTable(TAG)`

`InsertQuery.builder().table(TABLE).tags(TAG).build()`

@artem-zinnatullin, @thevery will it make sense or variant with [manual `notifyAboutChanges` call](https://github.com/pushtorefresh/storio/compare/dummy-table-changes?expand=1) is also applicable?

**Comment by artem-zinnatullin** [comment]
I'd start without API for manual notifyAboutChanges because DB operations
should be single source of true for such system. Let's see how users will
use this feature and if somebody will request manual API.

**Comment by Rainer-Lang** [comment]
I don't know if I'm right here....
I have a bunch of raw-sqls which affect different tables (I really don't know which exactly).
After executing these sqls I want to tell manually a defined set of "affected tables".
Is this now possible?

**Comment by nikitin-da** [comment]
Can't you call something like this?
```java
storIOSQLite
   .executeSQL()
   .withQuery(RawQuery.builder()
      .query("delete from users")
      .affectsTables(users) // table names here
      .build())
   .prepare()
   .executeAsBlocking();
```
Or what do you mean by `don't know which exactly`?

**Comment by Rainer-Lang** [comment]
Sorry, I should have provided more information.

I get a bunch of sqls from a server (during a sync process). I really don't now which tables are affected exactly.
I execute these sqls via ```executeSQL()```.
After processing all these sqls I want to to make a "manually affectedTables(syncTables)" at the end (not after every ```executeSQL()```).

worklflow
1) get sqls from server
2) ```executeSQL()``` every sql from 1)
3) at the end of 2): manual affectedTables(syncTables)

additional question:
Is it possible to give StorIO not only one sql, but a list of sqls to execute?

**Comment by nikitin-da** [comment]
When you call `executeSQL()` `DefaultStorIOSQLite` uses `sqlite#execSQL` and according to documentation for it:  `Multiple statements separated by semicolons are not supported.` =(

But you can generate the list of `PreparedOperation` and execute it inside transaction.
```java
class SqlFromServer {
   String statement;
   List<String> affectedTables;
}
...
storIOSQLite.lowLevel().beginTransaction();
try {
   for (SqlFromServer sqlFromServer : sqlsFromServer) {
      storIOSQLite
         .executeSQL()
         .withQuery(RawQuery.builder()
            .query(sqlFromServer.statement)
            .affectsTables(sqlFromServer.affectedTables)
            .build())
         .prepare()
         .executeAsBlocking();
   }
   storIOSQLite.lowLevel().setTransactionSuccessful();
} finally {
   storIOSQLite.lowLevel().endTransaction();
}
```
All notifications you'll receive after transaction end.

But anyway you have to know what tables you are updating, to prevent parsing sql statements manually. Can't server provide you with it?

**Comment by Rainer-Lang** [comment]
SyncTables: I know these tables.
Sqls: I know not exactly which tables they are affecting, but they are inside the "SyncTables".

@nikitin-da I like your example with transaction. I'll give it a try. Thanks a lot.

**Comment by Rainer-Lang** [comment]
What about ```notifyAboutChanges()``` after executing all sqls?

**Comment by nikitin-da** [comment]
If "SyncTables" - it is the set of affected tables by all statements, I guess it make sense to call manually `notifyAboutChanges()` in the end of transaction.

**Comment by Rainer-Lang** [comment]
@nikitin-da ```notifyAboutChanges()``` is working like a charm! :+1: 
And thanks for StorIO!
(Sorry, if this issue wasn't the right one to ask.)
