### ISSUE TITLE
Possible to get from a given class the resolver?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#670]

**Comment by nikitin-da** [comment]
Hi, @Rainer-Lang !
Sure, you can call 'storIOSQLite.lowLevel().typeMapping(AwesomeClass.class).putResolver()' / `storIOContentResolver.lowLevel().typeMapping(AwesomeClass.class).putResolver()`

**Comment by Rainer-Lang** [comment]
@nikitin-da Thanks a lot! Great!
