### ISSUE TITLE
Can I filter null object before asRxObservable() ?

### ISSUE THREAD

**Issue by XanderWang** [pushtorefresh/storio#671]
I use **storIO.get().listOfObjects().withGetResolver().asRxObservable()**  to observable database change.
But the  result is not I want, because my  GetResolver will return null object , when i show the chane result , i skip the null object . Can I filter null object before asRxObservable() ?

the version is
compile 'com.pushtorefresh.storio:sqlite:1.8.0'
compile 'com.pushtorefresh.storio:content-resolver:1.9.0'

**Comment by artem-zinnatullin** [comment]
What is `recorder`?

**Comment by XanderWang** [comment]
sorry,I did not describe clearly.There is no record in my database, it is empty

**Comment by artem-zinnatullin** [comment]
StorIO should notify you with empty result then. `storIO.get()…asRxObservable()` emits initial result.

In case of empty db: 

* `storIO.get().listOfObjects()` will emit empty `List` 
* `storIO.get().cursor()` will emit empty `Cursor` 
* `storIO.get().object()` will emit `null`

**Comment by XanderWang** [comment]
i find my error,  i use **storIO.get().listOfObjects()**  and my GetResolver will return null object, when i show GetResolver return data , i skip the null object , so i see no data in my app. Can i filter null object before **asRxObservable()**

**Comment by artem-zinnatullin** [comment]
Sorry, not sure I follow, can you please rewrite your question (if it is a question) "Can i filter null object before asRxObservable()"?

**Comment by artem-zinnatullin** [comment]
I'm closing this for now, feel free to comment!
