### ISSUE TITLE
Make public generated mapToInsertQuery, mapToUpdateQuery,...  methods

### ISSUE THREAD

**Issue by gbero** [pushtorefresh/storio#673]
For instance in the : https://github.com/pushtorefresh/storio/blob/master/storio-sqlite-annotations-processor/src/main/java/com/pushtorefresh/storio/sqlite/annotations/processor/generate/PutResolverGenerator.java
Modifiers are put as public for mapToContentValues, but not for mapToInsertQuery, mapToUpdateQuery, ...

It would be useful for when using storIOSQLite.lowLevel().insert() or .insertWithOnConflict() to be able to retrieve them.

I can do the PR for that if you want.

**Comment by nikitin-da** [comment]
Hi, @gbero! I think it make sense. 
@artem-zinnatullin what do you think?

**Comment by artem-zinnatullin** [comment]
I'm ~ok with that, but I'd like to leave them `final`
