### ISSUE TITLE
I need to execute a few thousands inserts.

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#679]
I have to handle a few thousands of inserts.
How could I do it efficiently?

**Comment by nikitin-da** [comment]
You should specify `useTransaction(true)`(by default already in transaction). 
If you're sure that these objects doesn't already present in db, you can use custom put resolver instead of `DefaultPutResolver` to eliminate cost for querying objects before insert.

**Comment by Rainer-Lang** [comment]
These inserts are raw sqls. So, no resolver would fit, right?

**Comment by Rainer-Lang** [comment]
I found a solution which doesn't help me right here because I have only the raw sqls...but I want to share it.

For bulk inserts there seems to be a fine class: InsertHelper
- http://orange-coding.net/2012/04/13/inserthelperandroid/
- http://www.outofwhatbox.com/blog/2010/12/android-using-databaseutils-inserthelper-for-faster-insertions-into-sqlite-database/

**Comment by nikitin-da** [comment]
`So, no resolver would fit, right?` 
Sure, with raw sql statement `putResolver` is useless.

`preInsertHelper` is deprecated right now. 
With raw `SQLiteOpenHelper` you can try [prepared statement](https://developer.android.com/reference/android/database/sqlite/SQLiteStatement.html) .
Something like this:
```java
void insertManyTweets(StorIOSQLite.LowLevel lowLevel, SQLiteOpenHelper helper, List<Tweet> tweets) {
    SQLiteDatabase db = helper.getWritableDatabase();
    try {
        db.beginTransaction();
        String sql = "INSERT INTO tweets (author_id, message) VALUES (?, ?)";
        SQLiteStatement statement = db.compileStatement(sql);
        for (Tweet tweet : tweets) {
            statement.clearBindings();
            statement.bindLong(1, tweet.authorId()); // 1-based index
            statement.bindString(2, tweet.Message());
            statement.executeInsert();
        }
        db.setTransactionSuccessful();
    } finally {
        db.endTransaction();
    }
    lowLevel.notifyAboutChanges(Changes.newInstance("tweets"));
}
```
