### ISSUE TITLE
question. Why safe toasts?

### ISSUE THREAD

**Issue by maxim-pandra** [pushtorefresh/storio#680]
Why sample app has this safe Toasts.java class. Are toast unsafe or something?
Is it common practice in big projects to have one? 
thx in advance =)

**Comment by Rainer-Lang** [comment]
Maybe of the context.

**Comment by maxim-pandra** [comment]
@Rainer-Lang can you provide some example or be a little more specific? 
I allways used Toasts and they never crashed. and i wasn't able to find information on this subject.

**Comment by artem-zinnatullin** [comment]
Huh, I don't remember precisely, I guess there was a case in our practice when Toast would not work with particular `Context`.

@nikitin-da maybe you remember something? :)

**Comment by nikitin-da** [comment]
I don't remember such cases=) 
I guess all types of context are acceptable and we should just check context for null 
(not to swallow `NotFoundException` if `stringRes` is incorrect or `RuntimeException` if we will call it from worker thread)

**Comment by skrzyneckik** [comment]
@nikitin-da I don't know am I correct but maybe this save toasts were added because of [potential 'race condition' when `AndroidSchedulers.mainThread()` is used](http://blog.bradcampbell.nz/keep-your-main-thread-synchronous/).

**Comment by artem-zinnatullin** [comment]
No, if you unsubscribe correctly there won't be a race condition
