### ISSUE TITLE
Possible to update only one column of a table?

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#682]
I have to update only one column - not the whole table.
I would use a custom PutResolver of course.

But what about the ```InsertQuery```?

**Comment by Rainer-Lang** [comment]
Just saw it - I could better use ```lowLevel().update()``` instead of ```lowLevel().insertWithOnConflict()```.

**Comment by nikitin-da** [comment]
If you are sure that row already exist, you can create put resolver like this:
```java
    class Tweet {
        private long id;
        private String author;
        private String text;
    }

    // Imagine we should update just text for specific tweet
    class UpdateTweetTextResolver extends PutResolver<Tweet> {

        @Override
        public PutResult performPut(StorIOSQLite storIOSQLite, Tweet tweet) {
            UpdateQuery query = UpdateQuery.builder()
                    .table("tweets")
                    .where("tweet_id = ?")
                    .whereArgs(tweet.id())
                    .build();
            final int numberOfRowsUpdated = storIOSQLite.lowLevel().update(query, mapToContentValues(tweet));
            return PutResult.newUpdateResult(numberOfRowsUpdated, query.table());
        }

        private ContentValues mapToContentValues(Tweet tweet) {
            ContentValues contentValues = new ContentValues(1);
            contentValues.put("tweet_text", tweet.text());
            return contentValues;
        }
    }
```
But I not sure I follow you, what do you mean by `need the UpdateQuery.builder().table(TABLE).build() and this is for all columns`?
If you want to update column across all rows, you can create query just once, otherwise you should specify target rows with specific `UpdateQuery`

**Comment by Rainer-Lang** [comment]
@nikitin-da Thanks a lot! Your example is great and helped.

**Comment by nikitin-da** [comment]
@Rainer-Lang you are welcome =)
