### ISSUE TITLE
16964 methods?? Seriously?

### ISSUE THREAD

**Issue by Aexyn** [pushtorefresh/storio#683]
I checked [Dbflow Method Count](http://www.methodscount.com/?lib=com.github.Raizlabs.DBFlow:dbflow-processor:3.1.1) and it shows 16964. Is it true or some bugs in counting methods ?

**Comment by Aexyn** [comment]
Sorry, wrong repo

**Comment by nikitin-da** [comment]
![true_story](https://cloud.githubusercontent.com/assets/7294857/18543208/501ff85c-7b37-11e6-81c2-f3b58f7a6f0e.png)
