### ISSUE TITLE
Create table inside Database 

### ISSUE THREAD

**Issue by pranavlathigara** [pushtorefresh/storio#690]
Hii
This library is useful for Put,Get and Delete function but my question is how to crate new database and table with use of this library..?

Thank you..

**Comment by nikitin-da** [comment]
Hi, @pranavlathigara!
For the new database you should create `SqliteOpenHelper` and pass it to `DefaultStorIOSQLite` [like this]( https://github.com/pushtorefresh/storio/blob/master/docs/StorIOSQLite.md#0-create-an-instance-of-storiosqlite)
For DDL operations like table creation, you can use [ExecSql](https://github.com/pushtorefresh/storio/blob/master/docs/StorIOSQLite.md#4-execsql-operation)

**Comment by pranavlathigara** [comment]
thank you....
