### ISSUE TITLE
Create tables using annotations only

### ISSUE THREAD

**Issue by jpventura** [pushtorefresh/storio#694]
Isn't it possible to create tables only defining _plain old text objects_ with StorIO annotations, just like it would be done using [SimontVT Schematic](https://github.com/SimonVT/schematic)?

**Comment by nikitin-da** [comment]
Actually with StorIO you can generate resolvers for get/put and delete operation [like this](https://github.com/pushtorefresh/storio/blob/master/docs/StorIOSQLite.md#how-object-mapping-works) but DDL request itself you should make manually or with some another tool

**Comment by AlexFrost** [comment]
Maybe it can generate Table classes form annotated POJOs using fields name, so we can use its in query. Because it is annoying to write all this columns name and set it back to POJO.

**Comment by nikitin-da** [comment]
Closed by #840 (Many thanks to @pbochenski and @geralt-encore )
Will be available in next release
