### ISSUE TITLE
Discussion on Rx and multiTable entities

### ISSUE THREAD

**Issue by ZakTaccardi** [pushtorefresh/storio#700]
In my opinion, SQL is painless until you start having to write joins. With Rx, "in-memory" joins, while less efficient, they are API friendly when using an operator like `.combineLatest()`. 

Problem: When observing a multi-table entity via `.combineLatest()`, a `put` operation using that entity results in multiple `onNext()` calls (because multiple tables are updated).

Let's say I have a `ShoppingCart` class, joined from data from two tables, `CartMeta` and `Items`.

```
data class ShoppingCart(
        val cartId: String,
        val invoiceNumber: String?,
        val isCheckedOut: Boolean,
        val items: List<Item>
) {
    val cartMeta = CartMeta(cartId, invoiceNumber, isCheckedOut)

    constructor(cartMeta: CartMeta, items: List<Item>) : this(
            cartId = cartMeta.cartId, invoiceNumber = cartMeta.invoiceNumber, isCheckedOut = cartMeta.isCheckedOut, items = items
    )
}

//backed by a "CartMeta" table
data class CartMeta(
        val cartId: String,
        val invoiceNumber: String?,
        val isCheckedOut: Boolean
)

//backed by a "Item" table
data class Item(
        val itemId: String,
        val price: String,
        val itemName: String
)
```

A `Put` operation on `ShoppingCart` would look like this.

```
        storIo.put()
                .`object`(shoppingCart.cartMeta)
                .prepare()
                .executeAsBlocking()

        storIo.put()
                .objects(shoppingCart.items)
                .prepare()
                .executeAsBlocking()
```

That generates a notification for the `CartMeta` table, and another for the `Items` table. I utilize `.combineLatest(cartMeta(), items())`, so I get two notifications here, when I want only one. I know `throttleLast()` could mostly fix this, but that introduces an delay (slower loads) and invites a race condition.

An API that would postpone notifications to the affected tables until both updates complete would fix this issue. Something like:

```
storIo.put()
                .`object`(shoppingCart.cartMeta)
                .`object`(shoppingCart.items)
                .prepare()
                .executeAsBlocking()
```

**Comment by nikitin-da** [comment]
Hi, @ZakTaccardi !
As a workaround to combine notifications you can put both objects in one transaction:
```java
storIo.lowLevel().beginTransaction();
try {
   storIo.put()
                .`object`(shoppingCart.cartMeta)
                .prepare()
                .executeAsBlocking();
   storIo.put()
                .`object`(shoppingCart.items)
                .prepare()
                .executeAsBlocking();
   storIOSQLite.lowLevel().setTransactionSuccessful();
} finally {
   storIOSQLite.lowLevel().endTransaction();
}
```

In case of putting few heterogeneous objects with one prepared operation: it will be tricky to specify put resolver for every kind of them.

**Comment by ZakTaccardi** [comment]
Thanks! 

Here's a kotlin extension function to wrap a transaction properly.

```
private fun StorIOSQLite.executeTransaction(function: () -> Unit) {
    this.lowLevel().beginTransaction()
    try {
        function.invoke()
        this.lowLevel().setTransactionSuccessful()
    } finally {
        this.lowLevel().endTransaction()
    }
}
```

Feel free to close this or leave it open (if you plan on some type of future 2.0 API improvement)

**Comment by nikitin-da** [comment]
Thanks, @ZakTaccardi, it looks pretty good!
Moreover if you would not want to deal with `lowLevel` and transaction you can add all objects into one list and then put it like this:
```java
   List<Object> objectsToPut = new ArrayList<>();
   objectsToPut.addAll(shoppingCart.cartMeta);
   objectsToPut.addAll(shoppingCart.items);
   storIo.put()
                .`object`(objectsToPut)
                .prepare()
                .executeAsBlocking();
```

About api changes: I thought about method in `StorIOSQLite` that takes multiple `PreparedOperation` and execute them in one transaction. 
But it may seems superfluous and there were plans to remove prepared operations at all.
@artem-zinnatullin what do you think?

**Comment by artem-zinnatullin** [comment]
Wwwwwait guys, as @nikitin-da mentioned, @ZakTaccardi you can just put all objects to one collection and perform Put operation over that collection, StorIO will wrap it into one transaction so I'm not sure you need this custom extension function. Moreover, with Kotlin it's about adding `listOf(obj1, obj2)` or `collection1 + collection2`. 

@ZakTaccardi we had such cases when we needed to observe changes from multiple tables and solution we found pretty good was to observe all changes, filter required tables and then flatMap/switchMap change to data loading, something like this:

```kotlin
storIO
  .observeChanges()
  .filter { it.affectedTables().let { it.contains("cart") || it.contains("items")  }
  .switchMap { Observable.merge(cartMeta().take(1), items().take(1)) }
```

Or if you want it to be even more efficient you can remove `filter` and add more complex `switchMap` that will load only changed table!

**Comment by artem-zinnatullin** [comment]
P.S. @ZakTaccardi, @nikitin-da  I'm very sorry for answering with such delays…

**Comment by nikitin-da** [comment]
Also #717 will help to handle it
