### ISSUE TITLE
So, what about ManyToMany sample? It would be very kind...

### ISSUE THREAD

**Issue by ValeriusGC** [pushtorefresh/storio#707]
Hi!
Alas, I can't understand how realize it in "StorIO-way"...
Earlier in #436 you referred on decision, but [excuse me my stupidity] I does not see it in storio-sample.
I see UserWithTweets which is OneToMany, but how realize M2M???

Thanks beforehand, BBK

**Comment by nikitin-da** [comment]
Hi, @ValeriusGC 
You can try something like this https://github.com/pushtorefresh/storio/pull/714
It is not trivial but StorIO is not ORM and there is no magic under the hood. 
So you should write such things as you normal code using existed type mapping.

**Comment by ValeriusGC** [comment]
Thanks, @nikitin-da 
I realize StorIO differs from ORM and have no thoughts to see "ORM-magic" in it )
All i'd like to see - recipe how to make it in elegant mode, with all of the power of this library.
The fact is not everything is always obvious in such complex projects.
And it seems you made it clearly, thanks.

**Comment by ValeriusGC** [comment]
Hi, @nikitin-da.
Look, something wrong happening in "on change subscription" in this sample.
It's about `Subscription subscribeToPersonsAndCars()` in **ManyToManyActivity**.
Every push for "add" or 'remove' car raises ever-increasing chain of calls.
I place logger in 
```
                        if (persons.isEmpty()) {
                            addPersons();
                        } else {
                            Log.i("FAFAFAFA-", persons.toString());
                            personsAdapter.setPersons(persons);
                        }
```
For first pressing on '+' i got 5 identical string. For second one - 7. Then pressed on '-' and got 10 log strings. And so on and so forth... How one should optimize this avalanche of 'parasite calls'?

**Comment by ValeriusGC** [comment]
I solved this by adding `.first()` operator before `.flatMap`. But maybe i do it wrong way? Maybe somewhere under the hood one should purge some buffer of affected tables?
