### ISSUE TITLE
Force implement all three resolver  ?

### ISSUE THREAD

**Issue by putt** [pushtorefresh/storio#709]
I just want do the GET action, and build the mapping like this:
.addTypeMapping(TicketWithCollection.class,
                        SQLiteTypeMapping.<TicketWithCollection>builder()
                                .putResolver(null)
                                .getResolver(new TicketWithCollectionGetResolver())
                                .deleteResolver(null)
                                .build())
But raise an nullexception.
Why storio force to implement all resolver, or just I'm doing the wrong way?

**Comment by nikitin-da** [comment]
Hi, @putt 
If you want to specify resolver for particular operation you can provide it like this
```java
storIOSQLite.get()
    .object(TicketWithCollection.class)
    .withQuery(Query.builder()
            .table(TicketWithCollectionTable.TABLE_NAME)
            .where(TicketWithCollectionTable.ID + "=?")
            .whereArgs(ticketId)
            .build())
    .withGetResolver(new TicketWithCollectionGetResolver())
    .prepare()
    .executeAsBlocking();
```
But, yes, it isn't allowed to add not complete type mapping to `StorIOSqlite` =(

**Comment by putt** [comment]
thanks, @nikitin-da . I perfer the Mapping way.
Now I find anonymous Resolver can get pass the null check. I think I will leave them in my DbModule ;)
.putResolver(new PutResolver<TicketWithCollection>() {
    @NonNull  @Override  
    public PutResult performPut(@NonNull StorIOSQLite storIOSQLite, @NonNull TicketWithCollection object) {    return null;   }
})

**Comment by nikitin-da** [comment]
Hah there are @NonNull and @Override users on github=)
@artem-zinnatullin should we check type mapping per operation and allow nullable resolver? 
In the bad case it will be runtime error too, so it does not seem to lose anything

**Comment by artem-zinnatullin** [comment]
Well, I don't want to accept `null` because it'll require us to add a lot of `if (resolver == null) throw UnsupportedOperationException` in different places…

@putt I think creating resolver that throws `UnsupportedOperationException` is much better approach. SGTY?

**Comment by nikitin-da** [comment]
Closing. Feel free to comment or reopen
