### ISSUE TITLE
Real exception has been swallowed during call chain

### ISSUE THREAD

**Issue by ValeriusGC** [pushtorefresh/storio#715]
When i tried make sql-query on non-existent table i got exception of type 
`android.database.sqlite.SQLiteException: no such table: persons (code 1): , while compiling: SELECT * FROM persons` in **PreparedGetListOfObjects.executeAsBlocking():122**.
But later going thru call chain this type was hidden and only `StorIOException("Error has occurred during Get operation. query...` was in error message.
imho this is not so clear as it may be.

**Comment by nikitin-da** [comment]
Yes, we wrap exception into StorIOException. 
Exception message should include query that may contain mistake.
But we don't swallow the original exception - it is places as cause. 
```java
throw new StorIOException("Error has occurred during Get operation. query = " + (query != null ? query : rawQuery), exception);
```
Are there original exception in stack trace?

**Comment by ValeriusGC** [comment]
Yes i saw that, thanks. But real error is not in "bad query" or something like that. Root mistake was in non-existence table. Maybe reasonable for show it for client? In my case i wasted some time and bulk of breakpoints to  solve the problem.

**Comment by artem-zinnatullin** [comment]
Cause of the exception should be shown in stacktrace with its message, wrapping should not be a problem!
