### ISSUE TITLE
Distinct not working with rawQuery

### ISSUE THREAD

**Issue by AlexAndroidDev** [pushtorefresh/storio#721]
Subscription sc = storIOSQLite
                .get()
                .listOfObjects(Tweet.class)
                .withQuery(RawQuery.builder()
                        .query("SELECT DISTINCT author FROM tweets")
                        .observesTables("tweets")
                        .build())
                .prepare()

                .asRxObservable()

                // Get Result as rx.Observable and subscribe to further updates of tables from Query!
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())

                .subscribe(tweet -> { // Please don't forget to unsubscribe
                            // Will be called with first result and then after each change of tables from Query
                            // Several changes in transaction -> one notification
                            tweetsAdapter.setTweets(tweets);
                        }
                );

It is statement not working! Thank you!

**Comment by nikitin-da** [comment]
We [directly pass](https://github.com/pushtorefresh/storio/blob/8a7d6aa4db6dfeece669dfefc3ed3e56f19df965/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/impl/DefaultStorIOSQLite.java#L336) query string from `RawQuery` to `SQLiteDatabase#rawQuery` without any modifications.
Do you have more specific example? Because in case of `tweets` from storIO you can't create `Tweet` object from `author` field only.
I've checked it on another example and haven't met any issues:
```java
        User user1 = User.builder().id("1").name("Jake").build();
        User user2 = User.builder().id("2").name("Jake").build();

        storIOSqlite
                .put()
                .objects(SolidList.list(userToPut, userToPut2))
                .prepare()
                .executeAsBlocking();

        Cursor cursor = storIOSqlite
                .get()
                .cursor()
                .withQuery(RawQuery.builder()
                        .query("SELECT DISTINCT name FROM users")
                        .build())
                .prepare()
                .executeAsBlocking();

        assertThat(cursor.getCount()).isEqualTo(1)
```

**Comment by nikitin-da** [comment]
Closed for now 
Feel free to reopen if you have some example (table structure and data) with witch we can meet this problem
