### ISSUE TITLE
What's the best way to put or update in case of conflict?

### ISSUE THREAD

**Issue by saket** [pushtorefresh/storio#728]
Hello!

Apart from using `DefaultStorIOSQLite#lowLevel()#insertWithOnConflict`, is there any other way I can use `DefaultStorIOSQLite#put()` which falls back to update if a row with the same primary eky already exists?

**Comment by artem-zinnatullin** [comment]
Yes, you can basically do whatever logic you want to do, ie query db to
find "existent" row and update it or remove it and insert new one, up to
you, just don't forget to put such logic into a transaction!
