### ISSUE TITLE
@artem-zinnatullin owes beer to @ZakTaccardi

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#733]
As continuation of #732 I'd like to file an issue  that I personally owe beer 🍻 to @ZakTaccardi for all his comments in threads on Reddit when he proves people that StorIO is able to do things they think it's not 😸 

@ZakTaccardi, whenever we'll be somewhere at the same time at ~same location -> feel free to ping me to go 🍻 and talk about software development things!

**Comment by skrzyneckik** [comment]
@artem-zinnatullin could you link to this Reddit thread? I would love to see it!

**Comment by artem-zinnatullin** [comment]
@skrzyneckik I believe you can just read [search results](https://www.reddit.com/r/androiddev/search?q=storio&sort=new&t=all), in some of them you'll see @ZakTaccardi answering :)

**Comment by artem-zinnatullin** [comment]
![img_20170927_021702](https://user-images.githubusercontent.com/967132/30898665-68794da6-a32a-11e7-83f1-5a40e3b9ec79.jpg)
