### ISSUE TITLE
Happy new year! 

### ISSUE THREAD

**Issue by Rainer-Lang** [pushtorefresh/storio#745]
And thanks for your hard work on this great lib.

**Comment by nikitin-da** [comment]
Thank you @Rainer-Lang! :christmas_tree: 
Happy new year and many thanks to everyone who use this library and make it better!
🎉 :confetti_ball:

**Comment by artem-zinnatullin** [comment]
Well, for about a year most of contributions to StorIO are done by @geralt-encore, so please thank him for work on the library :)

HNY!
