### ISSUE TITLE
GetResolver fails to generate properly with Kotlin nullable -> java boxed types

### ISSUE THREAD

**Issue by bluebery** [pushtorefresh/storio#749]
Hi everyone! This is my data class for a StorIO table with 5 columns using Kotlin

```
@StorIOSQLiteType(table = AttachmentTable.TABLE)
data class Attachment @StorIOSQLiteCreator constructor(
        @get:StorIOSQLiteColumn(name = AttachmentTable.COLUMN_MESSAGE_ID) val messageId: String,
        @get:StorIOSQLiteColumn(name = AttachmentTable.COLUMN_URL) val url: String,
        @get:StorIOSQLiteColumn(name = AttachmentTable.COLUMN_THUMBNAIL_URL) val thumbnailUrl: String,
        @get:StorIOSQLiteColumn(name = AttachmentTable.COLUMN_ID, key = true) var id: Long? = null,
        @get:StorIOSQLiteColumn(name = AttachmentTable.COLUMN_BYTES) var bytes: Long? = null)
```

And this is the generated AttachmentStorIOSQLiteGetResolver

```
    @Override
    @NonNull
    public Attachment mapFromCursor(@NonNull Cursor cursor) {

        String messageId = cursor.getString(cursor.getColumnIndex("messageId"));
        String url = cursor.getString(cursor.getColumnIndex("url"));
        String thumbnailUrl = cursor.getString(cursor.getColumnIndex("thumbnailUrl"));
        Longid= null;
        if(!cursor.isNull(cursor.getColumnIndex("_id"))) {
            id = cursor.getLong(cursor.getColumnIndex("_id"));
        }
        Longbytes= null;
        if(!cursor.isNull(cursor.getColumnIndex("bytes"))) {
            bytes = cursor.getLong(cursor.getColumnIndex("bytes"));
        }

        Attachment object = new Attachment(messageId, url, thumbnailUrl, id, bytes);

        return object;
    }
```

As you can see, everything appears correct except there is a space missing between the type (Long) and the variable name (id, bytes) causing a compilation error. Should be an easy fix? 

More examples of types (Kotlin -> Java Generated)
* Okay
** Long -> long
** String -> String

* Broken
** Long? -> Long
** Int? -> Integer

**Comment by geralt-encore** [comment]
Thanks for reporting the issue! I'll look into it soon.

**Comment by artem-zinnatullin** [comment]
Seems possible to handle via Kotlin reflection library (or something
similar), they write most of meta info as protobuffed base64 strings into
annotations (if I remember correctly).

**Comment by geralt-encore** [comment]
The problem was just in missing space for boxed types in Kotlin/AutoValue case. Now it's fixed and fix will be available in the next version.

**Comment by bluebery** [comment]
@geralt-encore thanks!!

**Comment by michaelcarrano** [comment]
I'm running into this issue too but not using Kotlin for my project.

**Comment by geralt-encore** [comment]
@michaelcarrano are you using AutoValue by any chance for you model?

**Comment by michaelcarrano** [comment]
@geralt-encore I am, and having issue with the Long type. The generated code is `Longid` like this issue.

**Comment by geralt-encore** [comment]
Then it's is the same problem and it has already been fixed in master branch.

**Comment by michaelcarrano** [comment]
@geralt-encore it took me a while debugging my app yesterday to figure out this was the issue I was running into. This ticket mentions Kotlin so wanted to make sure the issue would also be resolved for Java.

My app uses StorIO, Autovalue, Dagger, ButterKnife which all use processors. So kept getting led down the wrong path of where my actual issue was. I didn't know it was the StorIO Class getting generated incorrectly since Dagger kept complaining to me. So thought I had an issue with my Dagger implementation.

Thanks for fixing the issue, looking forward to a new release with the fix.

**Comment by artem-zinnatullin** [comment]
@geralt-encore if you want a new release, just discuss it with @nikitin-da, open (you or @nikitin-da) a PR with changelog and I'll publish it to Maven Central with no problems!

**Comment by artem-zinnatullin** [comment]
Moreover, I'm ok with small frequent releases, say once a week or so!

**Comment by geralt-encore** [comment]
@michaelcarrano glad that we resolved the issue and sorry for inconvenience since it has been introduced because of my mistake.
@artem-zinnatullin great! I've already created a PR for release https://github.com/pushtorefresh/storio/pull/756

**Comment by geralt-encore** [comment]
@bluebery @michaelcarrano please, verify that the issue was solved when 1.12.2 version will be available.

**Comment by artem-zinnatullin** [comment]
v1.12.2 should be available already!

**Comment by michaelcarrano** [comment]
@geralt-encore just had a chance to try out 1.12.2 and my issue is resolved. Thanks!

**Comment by artem-zinnatullin** [comment]
Great! Closing then.

**Comment by bluebery** [comment]
Hey thanks for fixing this @geralt-encore I'll give it a go as soon as I can!!
