### ISSUE TITLE
Should we add a Transformer on changs before the query task?

### ISSUE THREAD

**Issue by dannyjiajia** [pushtorefresh/storio#751]
As i known , each change object triggers a query task in `storio`. how can i filter the change before the query task?

should we  add another `asRxObservable` method in get operations?

https://github.com/pushtorefresh/storio/blob/master/storio-sqlite/src/main/java/com/pushtorefresh/storio/sqlite/operations/get/PreparedGetListOfObjects.java#L191 
~~~
public Observable<List<T>> asRxObservable(Observable.Transformer<Something, Something> tansformer) {
...
 observable = storIOSQLite
                    .observeChangesInTables(tables) 
                    .compose(tansformer)
                    .map(MapSomethingToExecuteAsBlocking.newInstance(this))
                    .startWith(Observable.create(OnSubscribeExecuteAsBlocking.newInstance(this))) // start stream with first query result
                    .onBackpressureLatest();
...
}
~~~

**Comment by nikitin-da** [comment]
Hi, @dannyjiajia !
Nice idea, it will simplify some cases.
I'll add it soon if guys will accept it 
//cc @artem-zinnatullin @geralt-encore

**Comment by artem-zinnatullin** [comment]
Wait, query will be reexecuted only if tables participated in it were
changed. Isn't that enough for most use cases?

**Comment by dannyjiajia** [comment]
@artem-zinnatullin @nikitin-da 
Hi guys, thanks your reply.That feature is enough for most use case.But i want to reduce the number of queries for database. 
Maybe there other ways?

**Comment by artem-zinnatullin** [comment]
There is a way, you can combine storio.get().asRxObservable().take(1) with
your Observable and only query db when you need, but I'd agree that it's
not so compact and convenient to use.

**Comment by dannyjiajia** [comment]
@artem-zinnatullin thanks your reply. It's works. 👍
