### ISSUE TITLE
Handling constraint exceptions properly

### ISSUE THREAD

**Issue by komigor** [pushtorefresh/storio#759]
As I started testing my database logic code, I need an opportunity to handle different SQLite exceptions like Unique constraint failed, as some of the operations are very important. So the question is - how can I do it with StorIOSQLite, as it throws its own Exceptions, that contains no data that making it able to detect the reason of exception raising programmatically.

**Comment by nikitin-da** [comment]
Hi, @komigor !
We wrap exception into StorIOException, and the original one places as cause.
```java
throw new StorIOException("Error has occurred during Get operation. query = " + (query != null ? query : rawQuery), exception);
```
Are there original exception in stack trace?

**Comment by komigor** [comment]
Yep, thx for that. Didn't notice them because of enormous size of stacktrace

**Comment by nikitin-da** [comment]
No problem) Closing for now. Feel free to comment or reopen
