### ISSUE TITLE
v1.13.0 milestone

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#767]
Let's discuss what to include into next minor release?

I vote for RxJava v2 support #685 and notification tags #663 (recently discussed offline with @nikitin-da, @geralt-encore if you need more info — feel free to ask in #663!).

**Comment by nikitin-da** [comment]
RxJava2 is very desired especially for people who start new project. It may be deciding factor in the choice of the library.
I've already started to make notification tags. I hope long holidays will help me to finish it this week)

**Comment by artem-zinnatullin** [comment]
Oh cool! So let's wait for @geralt-encore opinion and set milestones on issues accordingly! (I hope you guys have rights for that)

**Comment by geralt-encore** [comment]
I can look into RxJava 2 migration. Have we agreed on how precisely we are gonna do it?

> What about using interop library internally? Completely migrate to v2 and provide methods for v1 interop via the library. Then just wipe it after some time.

Is this still a viable option?

**Comment by artem-zinnatullin** [comment]
>Is this still a viable option?

Yup, I think so, but we'll need to either copy it or repackage so it would not conflict with user-added one.

**Comment by geralt-encore** [comment]
Can't we just check if it is in class path same as with RxJava atm?

**Comment by artem-zinnatullin** [comment]
We can, but I'm afraid there could be potential breaking changes that we would have to check for and be ready for fast releases just to fix them…

**Comment by geralt-encore** [comment]
Ok, got it, makes sense. But I think that we still need some kind of a more detailed roadmap or plan because this feature is far too big and important for implementing just by me with the current vague idea how to tackle it.

**Comment by artem-zinnatullin** [comment]
Sure, both me and @nikitin-da (I hope lol) will provide help. 

Actually, let's ask David,

@akarnokd, can you please consult us if it'll be ok to depend on your [RxJava2Interop](https://github.com/akarnokd/RxJava2Interop) library in our library, or should we repackage it to avoid conflicts with user-added one? 

TL;TR: how stable are APIs in [RxJava2Interop](https://github.com/akarnokd/RxJava2Interop)?

**Comment by akarnokd** [comment]
The API in `RxJava2Interop` is stable in the sense that what's currently there won't change but may be extended with further conversions (for example Scheduler conversion is possible in the near future).

Internally, there are some dependencies on internal features of RxJava which I keep up to date whenever 1.x or 2.x releases but the algorithms themselves are fairly final and bug-free.

To be on the safe side, I suggest you take the conversions your library requires by the source (and the sources of the internal dependencies from either RxJava version) and have it in your project internally.

**Comment by artem-zinnatullin** [comment]
@akarnokd thanks for detailed answer! Sounds like it's pretty safe to depend on your library in our case.

>To be on the safe side, I suggest you take the conversions your library requires by the source (and the sources of the internal dependencies from either RxJava version) and have it in your project internally.

We're not planning to support both RxJava v1 and v2 for a long time and it's more about providing better APIs for a time frame of migration from RxJava v1 to v2 for developers in their projects.

In StorIO v2.0 we'll drop RxJava v1 support, and in any critical case we can always rollout update with repackaged version of your interop library.

@geralt-encore let's then simply add RxJava v2 and RxJava2Interop as `provided` dependencies and do basically the same things we do for optional RxJava v1 support?

**Comment by geralt-encore** [comment]
Sounds good! Also, we have to do something with `nulls` in `object` methods.

**Comment by nikitin-da** [comment]
Maybe we can release already merged requests [annotation processor on Kotlin](https://github.com/pushtorefresh/storio/pull/775), [Kotlin properties support](https://github.com/pushtorefresh/storio/pull/776) and [tags](https://github.com/pushtorefresh/storio/pull/768).
[Interceptors](https://github.com/pushtorefresh/storio/pull/771) will break current api, so it should be 2.0. Should we move rxjava 2 support to 2.0 milestone too?

**Comment by artem-zinnatullin** [comment]
I agree, let's release v1 with kotlin improvements and tags, I've moved Interceptors to v2, let's move RxJava2 to v2 as well.

When you want me to make v1 release?

**Comment by geralt-encore** [comment]
I'll try to start working on RxJava2 support. It just looks too big so I am scared every time when I am thinking about starting it 😔

**Comment by nikitin-da** [comment]
@artem-zinnatullin What about tomorrow? (#787)

**Comment by artem-zinnatullin** [comment]
1.13.0 was released, closing the issue :)
