### ISSUE TITLE
Proguard and StorIO

### ISSUE THREAD

**Issue by Tooto** [pushtorefresh/storio#773]
Hi!
Should i setup some proguard rules?
I have this error:
Warning:com.pushtorefresh.storio.operations.internal.OnSubscribeExecuteAsBlockingCompletable: can't find superclass or interface rx.Completable$OnSubscribe

**Comment by artem-zinnatullin** [comment]
I guess you don't use RxJava. StorIO does not use reflection that requires
proguard settings.

**Comment by nikitin-da** [comment]
I guess the only issue we can meet with obfuscation is the false negative result in [this](https://github.com/pushtorefresh/storio/blob/9f93ee905e70d6c89290e094a92ddcdb57df0e45/storio-common/src/main/java/com/pushtorefresh/storio/internal/Environment.java#L22) check
Do you have explicit rxjava dependency?

**Comment by artem-zinnatullin** [comment]
AFAIK, ProGuard handles such class lookups.

**Comment by artem-zinnatullin** [comment]
I'm closing the issue, feel free to comment!

**Comment by karntrehan** [comment]
For anybody facing this issue. Please use the following line in your proguard-rules.pro
`-dontwarn com.pushtorefresh.storio.**`
