### ISSUE TITLE
all auto generated resolvers disappeared

### ISSUE THREAD

**Issue by TonyNikolov** [pushtorefresh/storio#783]
I've been trying out storIO for 2 days and i've been having great results, untill today. I started Android Studio and all auto generated resolver classes are gone and i cant even build my project.

`Error:(9, 53) error: cannot find symbol class CommentStorIOContentResolverDeleteResolver`
`Error:(10, 53) error: cannot find symbol class CommentStorIOContentResolverGetResolver`
`Error:(11, 53) error: cannot find symbol class CommentStorIOContentResolverPutResolver`

These used to be auto generated classes, that are no longer appearing. I tried Clean Project, Rebuild Project, restarted my pc, android studio... I have no idea whats the problem.

**Comment by TonyNikolov** [comment]
Looks like something with annotation processors went wrong, still dont know what it was, but its working now.

**Comment by miralas** [comment]
I'm having similar issue now. After migration to AndroidX and update to storio3  all auto generated storio resolvers and mappings are gone. I have no idea whats going on.
