### ISSUE TITLE
Add example of integration with SQLDelight

### ISSUE THREAD

**Issue by nikitin-da** [pushtorefresh/storio#785]
https://github.com/square/sqldelight

**Comment by artem-zinnatullin** [comment]
Great idea! Since you successfully use it in production with StorIO you're very good source of info, maybe also write a blog article (or even markdown post here in repo) with your story?

**Comment by thevery** [comment]
We're going into production in couple of weeks I hope :)
During migration we've faced several issues in both sqldelight and storio, but most of them (except https://github.com/pushtorefresh/storio/issues/704) are already resolved!

**Comment by thevery** [comment]
I think that we should start we some sample anyway, what project structure should we use for it? @artem-zinnatullin

**Comment by artem-zinnatullin** [comment]
Completely up to you, I think you can basically copy-paste current sample (it's pretty simple to look at) and just replace/add queries with SQLDelight

**Comment by nayeemzen** [comment]
Any updates on this? Would love to see an example!

**Comment by nikitin-da** [comment]
I'm really sorry for such delays, I don't have time right now =(
I hope I will open request in two weeks

**Comment by thevery** [comment]
Same here :(

**Comment by nikitin-da** [comment]
@nayeemzen sorry for such delay =(
I have opened request with this example
The main idea is to use mapping generated by SQLDelight for complex objects: [serialization](https://github.com/pushtorefresh/storio/pull/814/files#diff-93af467e4d57f246c5122de1e62924a4R127) and [deserialization](https://github.com/pushtorefresh/storio/pull/814/files#diff-93af467e4d57f246c5122de1e62924a4R90)
StorIO will be helpful in such case mainly for rx and notifications
