### ISSUE TITLE
Lowering minSdkVersion to 9 for further compatibility

### ISSUE THREAD

**Issue by Thore1954** [pushtorefresh/storio#795]
This is a great lib and I use it in most of my projects except the one's the client asks to be compatible down to Android 2.3! Any idea on lowering the minSdkVersion to API 9 somewhere in the future?
I don't think it takes much effort since most everything in the lib is already back compatible.

**Comment by artem-zinnatullin** [comment]
Well, such a commitment will definitely tie our hands for future releases..

I belive you can override our minSdk in your project setup!

**Comment by Thore1954** [comment]
Yes, you were right. I managed to add the `storio-common` and `storio-sqlite` modules directly into my project and with a few modifications on gradle files it worked on Android 2.3!
I still don't understand why lowering the minSdkVersion will make problem on this Non-UI library.

**Comment by artem-zinnatullin** [comment]
>I managed to add the storio-common and storio-sqlite modules directly into my project and with a few modifications on gradle files it worked on Android 2.3!

That's not what I meant 😨 

You should be able to override StorIO/s minSdk just by adding something like this in your `AndroidManifest.xml`:

```xml
<uses-sdk 
  tools:overrideLibrary="com.pushtorefresh.storio.common" 
  tools:overrideLibrary="com.pushtorefresh.storio.sqlite" />
```

>I still don't understand why lowering the minSdkVersion will make problem on this Non-UI library.

Well, it might look easy now, but we may use some SQLiteDatabase/ContentResolver methods that are API level dependent and in such a case we'll be in a bad situation with low minSdkVersion.
