### ISSUE TITLE
Release v2.0.0 preparations.

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/storio#809]
See https://github.com/pushtorefresh/storio/milestones/v2.0.0

@geralt-encore @nikitin-da I've cleaned up issues assigned to this milestone, can you please take care of remaining issues?

It'll probably be better if I actually perform the release once all issues will be closed, because it might not work on Travis right away and I may have to apply appropriate fixes or in worst case release manually.

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by nikitin-da** [comment]
@Rainer-Lang sorry for delay( All tasks are resolved. So we may prepare release tomorrow.

**Comment by Rainer-Lang** [comment]
Thanks. :+1:
