### ISSUE TITLE
Android Studio Open storio-sample-app (error)

### ISSUE THREAD

**Issue by hui5368** [pushtorefresh/storio#810]
Hi, when i was trying to open storio-sample-app using android studio, but i have some error about 
 **_CreateProcess error=2, The system cannot find the file specified_**.

Does anyone knows how to fix this problem ?

**Comment by nikitin-da** [comment]
Hi, @hui5368 ! Do you have 'git' in path?
Can you please provide whole stacktrace?

**Comment by nikitin-da** [comment]
Closing. Feel free to reopen if adding `git` to path doesn't solve problem
