### ISSUE TITLE
Delete all objects and put in one operation with only one notification of observables

### ISSUE THREAD

**Issue by Verichev** [pushtorefresh/storio#811]
I would like just to replace all content of a table with new content. To do this I use two operations "delete" and then "update". But my subscribed observables receive two notifications in this case. How can I avoid notification after deleting table content or is there any all-in-one operation for replacting all content in a table?

**Comment by artem-zinnatullin** [comment]
You can do it in a transaction:

```kotlin
storIOSQLite.lowLevel().beginTransaction()

try {
  // perform operations here
  storIOSQLite.lowLevel().setTransactionSuccessful()
} finally {
  storIOSQLite.lowLevel().endTransaction()
}
```

Please do it off the main thread!
