### ISSUE TITLE
Implement one-to-many relationship

### ISSUE THREAD

**Issue by nikiJava** [pushtorefresh/storio#815]
Would you please provide an example of one-to-many relationship implementation?
Is ti possible to use it with FOREIGN KEY parameter in creaate table query?

**Comment by nikitin-da** [comment]
@nikiJava, there is already such example [here](https://github.com/pushtorefresh/storio/blob/master/storio-sample-app/src/main/java/com/pushtorefresh/storio2/sample/db/entities/UserWithTweets.java#L30) and [here resolver](https://github.com/pushtorefresh/storio/blob/master/storio-sample-app/src/main/java/com/pushtorefresh/storio2/sample/db/resolvers/UserWithTweetsGetResolver.java#L48) for it.
It seems there should not be problems with `FOREIGN KEY`
Feel free to reopen if you will meet some troubles
