### ISSUE TITLE
subscribe not found on asRxSingle!

### ISSUE THREAD

**Issue by rezaiyan** [pushtorefresh/storio#828]
```
  StorIOFactory.get(this)
                .put()
                .objects(table)
                .prepare()
                .asRxSingle()
                .subscribe(); // not found method :/
```

what's my problem

**Comment by rezaiyan** [comment]
The problem is because storio using rxjava1 but i used rxjava2!
how can solve it?

**Comment by nikitin-da** [comment]
@rezaiyan sorry, but we didn't finish rxjava2 support yet( https://github.com/pushtorefresh/storio/issues/685
For now you can use https://github.com/akarnokd/RxJava2Interop but it will force you to have dependencies to both versions(
