### ISSUE TITLE
Security certificate of pushtorefresh.com was expired 267 days ago

### ISSUE THREAD

**Issue by AlexTrotsenko** [pushtorefresh/storio#838]
Documentation -> Why we made StorIO refers _pushtorefresh.com_. When opened, browser shows security warning:
```
This server could not prove that it is pushtorefresh.com; its security certificate expired 267 days ago
```
![screen shot 2017-10-17 at 10 55 19](https://user-images.githubusercontent.com/4673265/31655548-81250fa2-b329-11e7-925e-1926abdb28fd.png)

**P.S.** 2 more links are broken:
- Design tests for StorIO SQLite
- Design tests for StorIO ContentResolver

**Comment by nikitin-da** [comment]
@AlexTrotsenko thanks!

**Comment by artem-zinnatullin** [comment]
Oh man, nostalgia

<img width="953" alt="screen shot 2017-10-17 at 05 13 07" src="https://user-images.githubusercontent.com/967132/31664349-eed512a2-b2f9-11e7-89f2-68160771963f.png">

Ideally we should bring that article to the docs folder in repository
