### ISSUE TITLE
Support io.reactivex.Maybe

### ISSUE THREAD

**Issue by geralt-encore** [pushtorefresh/storio#846]
I'll work on this as soon as initial RxJava 2 support will be merged

**Comment by nikitin-da** [comment]
It will be great!

**Comment by geralt-encore** [comment]
I've started to look into Maybe implementation and not everything is quite clear.  
To be able to properly implement `MaybeOnSubscribeExecuteAsBlocking` there has to be a way to distinguish between empty and non-empty cases. Since `Result` is generic the only way to achieve it is to make `executeAsBlocking` nullable again. Is it ok or am I missing something?

**Comment by geralt-encore** [comment]
Another question. What will be correct for empty list/cursor cases: to return an empty list/cursor or to just complete stream without an emission?

**Comment by nikitin-da** [comment]
Dumn, my bad=( 
`preparedOperation`'s `Result` must be must be `Optional` and unwrapperd nullable value at the same time =(

Maybe we should create separate `WrappedResult` generic type, that will duplicate `Result` for `listOfObject` and `cursor`?

Otherwise, if we are ok that result of `Maybe` is `Optional` than we can create separate `MaybeOnSubscribeExecuteAsBlocking` implementations for `Optional<T>`, `List<T>` and so on.

//cc @artem-zinnatullin 

>What will be correct for empty list/cursor cases: to return an empty list/cursor or to just complete stream without an emission?

I guess we should complete stream without an emission, otherwise it will be the same `asRxSingle`

**Comment by geralt-encore** [comment]
> I guess we should complete stream without an emission, otherwise it will be the same asRxSingle
Had the same thoughts and just wanted to verify it.

Not sure if I got what you were saying about `preparedOperation`'s `Result`.
Isn't actual wrapping happens on `Interceptor` level so we can return null for `Maybe` case and still be able to use `Optional` for `Single`?

**Comment by nikitin-da** [comment]
Not quite so, interceptor must return value of [the same type](https://github.com/pushtorefresh/storio/blob/5850b7e450b5d58498fbc5acf23076cb055b578b/storio-sqlite/src/main/java/com/pushtorefresh/storio2/sqlite/Interceptor.java#L15) as [prepared operation uses](https://github.com/pushtorefresh/storio/blob/5850b7e450b5d58498fbc5acf23076cb055b578b/storio-sqlite/src/main/java/com/pushtorefresh/storio2/sqlite/operations/get/PreparedGet.java#L21)
So all other methods (`executeAsBlocking`, "asRxFlowable") must returns values with the same type =(

**Comment by geralt-encore** [comment]
Yeah, now I see... Have to think more about it then

**Comment by nikitin-da** [comment]
As I said before maybe we can add `WrappedResult` type in prepared operation declaration 
`executeAsBlocking`, `asRxMaybe` and interceptors will continue to work with `Result`, nut `asRxSingle` and `asRxFlowable` will return `WrappedResult`. That will be `Optional` only for `PreparedGet`.
So `SingleOnSubscribeExecuteAsBlocking` and `FlowableOnSubscribeExecuteAsBlocking` will be responsible for optional creation

**Comment by geralt-encore** [comment]
I'll look into it tomorrow with a clear head =)

**Comment by nikitin-da** [comment]
I will prepare some draft for this idea in 2 hours

**Comment by nikitin-da** [comment]
I suppose something like [this](https://github.com/pushtorefresh/storio/pull/856)
