### ISSUE TITLE
How to add a composite primary key?

### ISSUE THREAD

**Issue by MarinKacaj** [pushtorefresh/storio#853]
I have a table with a composite primary key of two columns.
The generated table creation code throws a SQLiteException, because the syntax of the composite primary key in there is not correct: it declares both columns as primary keys instead of declaring the primary key separately, with both columns next to it, in parentheses.
Please see [this SO question about this issue in SQLite](https://stackoverflow.com/questions/734689/sqlite-primary-key-on-multiple-columns).

**Comment by nikitin-da** [comment]
@MarinKacaj thank you for report!
