### ISSUE TITLE
Error when trying to upgrade to latest version

### ISSUE THREAD

**Issue by sreejithraman** [pushtorefresh/storio#860]
I get these 2 errors: 
````
Failed to resolve: com.pushtorefresh.storio3:sqlite:2.0.0
Failed to resolve: com.pushtorefresh.storio3:sqlite-annotations:2.0.0
`````
Here's what I included in the gradle file:
````
  compile 'com.pushtorefresh.storio3:sqlite:2.0.0'
  compile 'com.pushtorefresh.storio3:sqlite-annotations:2.0.0'
  annotationProcessor 'com.pushtorefresh.storio3:sqlite-annotations-processor:2.0.0'
`````

What am I doing wrong? 

Just fyi, the old ver. still works for me:
````
  compile 'com.pushtorefresh.storio:sqlite:1.13.0'
  compile 'com.pushtorefresh.storio:sqlite-annotations:1.13.0'
  annotationProcessor 'com.pushtorefresh.storio:sqlite-annotations-processor:1.13.0'
````

**Comment by geralt-encore** [comment]
You need to use `storio2` instead of `storio3`. Sorry about the wrong info in readme - it is updated for the next version which has not been released yet.

**Comment by nikitin-da** [comment]
Sorry guys I hurried to bump version but v3 hasn't published yet
I think we should migrate to [AGP3](https://github.com/pushtorefresh/storio/issues/851) resolve linked [issue](https://github.com/pushtorefresh/storio/issues/852) and add interceptors for content resolver (It will break api too and publishing the third major version for a short time does not sound good)
@mohaxspb currently rollback changes in readme #861
