### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [pushtorefresh/storio#874]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by artem-zinnatullin** [comment]
Dude, this is third project I'm part of where you create this issue, such promotion is not okay, especially asking to star the repo.

I see same issue again — I report as spam, nothing personal.

**Comment by oleksiyp** [comment]
Sorry for that. Most of feedbacks after are very positive or just "close issue". You're probably participating many projects. Sending is finnished, so you shouldnt get more messages, except already seng today
