### ISSUE TITLE
Using StorIO with AndroidX and Jetifier

### ISSUE THREAD

**Issue by fstephany** [pushtorefresh/storio#893]
We are converting one of our project to AndroidX and the jetifier seems to choke on the `@NonNull` annotation in the generated resolver (e.g., `mapFromCursor(@NonNull ...`)

When compiling we have `Cannot find symbol` on the `NonNull` symbol. This is probably because the jetifier did not convert  `com.android.support:support-annotations` into  `androidx.annotation:annotation:1.0.0-alpha1` .

Anyone else ran into this as well? 
Is there any will to migrate from the support libs to AndroidX?

**Comment by fstephany** [comment]
@RocketRider We still don't know if we'll patch+PR or migrate to another framework.

**Comment by nikitin-da** [comment]
Hi guys!
Many sorry for delay
Jetifier rewrites binaries of third-party code, but it seems can't handle generated by this library classes =(
Hopefully I will publish both annotation types support in this weekend

**Comment by fstephany** [comment]
Thanks @nikitin-da  ! 
If you need help over the weekend, do not hesitate to ask =)

**Comment by nikitin-da** [comment]
Hi @artem-zinnatullin !
I saw butterknife issue. Jake [says](https://github.com/JakeWharton/butterknife/issues/1270#issuecomment-387584304) that it is tooling bug. There is [issue](https://issuetracker.google.com/issues/110374389) in the tracker but with status new.
In the next butterknife release (v9.0) they will publish [fix](https://github.com/JakeWharton/butterknife/pull/1289/files#diff-141a2db288c994f07eba0c49a2869e9bR1363) on the library side.

**Comment by artem-zinnatullin** [comment]
Thanks for links 👍 

// It's amazing how many things they were able to break with this change, uhh

**Comment by nikitin-da** [comment]
Nobody likes annotation processing =/
