### ISSUE TITLE
executeSQL() not able to use asRxCompletable()

### ISSUE THREAD

**Issue by efthymios1991** [pushtorefresh/storio#904]
I recently updated my project to the last version of `storIO`. Based on the release notes of version 3 i should be able to use `asRxCompletable()` for my `executeSQL()` queries, but i still don't have that option.

**Comment by nikitin-da** [comment]
Hi @efthymios1991 !
Uhh my bad( This issue was closed by mistake
https://github.com/pushtorefresh/storio/pull/857 should close PR# 855 instead of Issue# 855
And I grep it to changelog :see_no_evil: 
I will add it soon, thank you for notice
